package web

import (
	"crypto/sha256"
	"embed"
	"encoding/hex"
	"io/fs"
	"net/http"
	"path"
	"strings"
	"sync"

	"github.com/kingzion24/ozymandis/internal/web/ui/utils"
)

// Compiled CSS is embedded rather than served from disk, so the binary is the
// whole deployment. A self-hoster copying one file to a server and running it
// is the distribution story; an app that needs its assets directory alongside
// it is not.
//
// assets/css/app.css is generated by `make css` (Tailwind) and committed, which
// is what keeps `go build` working for anyone who has not installed the
// Tailwind CLI. CI verifies the committed output is current.
//
//go:embed all:assets
var assetsFS embed.FS

// assetFingerprints maps an asset path to a short content hash.
//
// Populated once, lazily, from the embedded files. The hash goes in the query
// string so the CSS can be cached for a year and still change the moment a
// deploy changes it — without which a returning operator sees the old
// stylesheet against new markup.
var (
	fingerprintOnce sync.Once
	fingerprints    map[string]string
)

func computeFingerprints() {
	fingerprints = map[string]string{}
	_ = fs.WalkDir(assetsFS, "assets", func(p string, d fs.DirEntry, err error) error {
		if err != nil || d.IsDir() {
			return nil
		}
		b, readErr := assetsFS.ReadFile(p)
		if readErr != nil {
			return nil
		}
		sum := sha256.Sum256(b)
		fingerprints["/"+p] = hex.EncodeToString(sum[:])[:10]
		return nil
	})
}

// asset returns a URL for an embedded asset, fingerprinted for cache busting.
func asset(urlPath string) string {
	fingerprintOnce.Do(computeFingerprints)
	if h, ok := fingerprints[urlPath]; ok {
		return urlPath + "?v=" + h
	}
	return urlPath
}

// The vendored templUI components ask for their JavaScript through this
// variable. Pointing it at asset gives them the same fingerprinting as
// everything else, instead of upstream's process-start timestamp — which would
// change on every restart and throw away a cache that had not gone stale.
func init() { utils.ScriptURL = asset }

// assetHandler serves the embedded assets.
func assetHandler() http.Handler {
	sub, err := fs.Sub(assetsFS, "assets")
	if err != nil {
		// Only reachable if the embed directive and this path disagree, which
		// is a build-time mistake rather than a runtime condition.
		panic("web: assets not embedded: " + err.Error())
	}
	// The sub-FS is already rooted at assets/, so the URL's own /assets prefix
	// has to come off or every lookup misses by one directory.
	files := http.StripPrefix("/assets", http.FileServer(http.FS(sub)))

	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		// Fingerprinted requests are immutable by construction. Unfingerprinted
		// ones might be a hand-typed URL, so they get a short cache instead.
		if r.URL.Query().Get("v") != "" {
			w.Header().Set("Cache-Control", "public, max-age=31536000, immutable")
		} else {
			w.Header().Set("Cache-Control", "public, max-age=300")
		}

		// http.FileServer infers most types, but not reliably for .css served
		// from an io/fs on every platform.
		if strings.HasSuffix(path.Base(r.URL.Path), ".css") {
			w.Header().Set("Content-Type", "text/css; charset=utf-8")
		}

		files.ServeHTTP(w, r)
	})
}
