// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package web

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// Brand marks, inlined from assets/brand.
//
// Inlined rather than served as files for two reasons. The wordmark is drawn in
// currentColor, so it follows the theme instead of being black on a dark page —
// an <img> cannot do that without shipping two files that can disagree. And the
// mark appears in the collapsed rail, where a second request would leave a gap
// on every navigation.
//
// The two teals in the mark are the brand's own, and --brand is set from the
// same values, so the interface and the logo cannot drift apart.

// brandMark is the mark: the sidebar, and anywhere too small for a name.
//
// The wordmark that used to sit beside it is gone. It drew the name as vector
// letterforms, which is a way of writing a name that no search can find — and
// it still spelled Yacht long after the rename. The name is text now.
//
// width and height are on the element, not only in the viewBox. Without an
// intrinsic size a `w-auto` has nothing to resolve against, and an SVG in a
// flex row collapses to zero — which is what the text it replaced never did.
func brandMark(class string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		var templ_7745c5c3_Var2 = []any{class}
		templ_7745c5c3_Err = templ.RenderCSSItems(ctx, templ_7745c5c3_Buffer, templ_7745c5c3_Var2...)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<svg class=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.ResolveAttributeValue(templ.CSSClasses(templ_7745c5c3_Var2).String())
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/web/brand.templ`, Line: 1, Col: 0}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var3)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\" width=\"215\" height=\"292\" viewBox=\"0 0 215 292\" xmlns=\"http://www.w3.org/2000/svg\" role=\"img\" aria-label=\"Ozymandis\"><g transform=\"matrix(1,0,0,1,-958.482024,-1596.092892)\"><g transform=\"matrix(0.508174,0,0,0.48621,221.930828,929.700086)\"><path d=\"M1870.593,1721.574L1790.154,1969.141L1529.846,1969.141L1449.407,1721.574L1660,1568.569L1870.593,1721.574ZM1692.973,1910.195L1747.327,1910.195L1801.298,1744.09L1660,1641.431L1518.702,1744.09L1572.673,1910.195L1627.027,1910.195L1660,1753.544L1692.973,1910.195Z\" style=\"fill:rgb(33,149,132);\"></path></g> <g transform=\"matrix(0.553013,0,0,0.736836,224.367075,528.603688)\"><path d=\"M1380,1587.606L1380,1635.684L1521,1562.122L1662,1635.684L1662,1587.606L1521,1514.043L1380,1587.606Z\" style=\"fill:rgb(74,168,154);\"></path></g> <g transform=\"matrix(0.553013,0,0,0.529111,223.814062,870.10361)\"><path d=\"M1438,1500.076L1438,1433.122L1522,1372.093L1606,1433.122L1606,1500.076L1522,1439.047L1438,1500.076Z\" style=\"fill:rgb(74,168,154);\"></path></g></g></svg>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
