-- +goose Up
-- +goose StatementBegin

-- Deploy on push.
--
-- Until now a repository app rebuilt when somebody clicked, and a private
-- repository could not be cloned at all — the build's clone step runs
-- unauthenticated. These four columns close both.

-- Whether a push should deploy this app at all.
--
-- Off by default and per app rather than per install: an app somebody is still
-- setting up should not start deploying because a colleague pushed, and the
-- decision belongs with the app because that is where the repository is named.
ALTER TABLE apps ADD COLUMN auto_deploy boolean NOT NULL DEFAULT false;

-- The shared secret GitHub signs its deliveries with, sealed.
--
-- Per app, not per install. One secret for everything would mean any repository
-- with a webhook configured could trigger a deploy of any app — the signature
-- would verify, because it is the same key — and the payload's repository field
-- is attacker-controlled, so it cannot be the thing that decides which app is
-- deployed. A per-app secret makes the signature itself the scoping.
--
-- Sealed with OZYMANDIS_SECRET_KEY like every other credential here: a database
-- dump must not be a set of working webhook signatures.
ALTER TABLE apps ADD COLUMN webhook_secret bytea;

-- The private half of a deploy key, sealed. NULL means none has been generated.
--
-- ed25519 rather than RSA: shorter, faster, and supported by every Git host
-- worth naming. Generated by this engine rather than pasted in, so the private
-- half exists in exactly one place and nobody is tempted to reuse a personal
-- key that opens every repository they can see.
ALTER TABLE apps ADD COLUMN deploy_key bytea;

-- The public half, readable, because its whole purpose is to be copied into a
-- repository's settings. Not sealed: it is public by construction.
ALTER TABLE apps ADD COLUMN deploy_key_public text NOT NULL DEFAULT '';

-- The commit last deployed, so a redelivered webhook does not build it again.
--
-- GitHub redelivers on its own schedule and a person can replay a delivery from
-- the UI, so "did I already build this" has to be answerable from state rather
-- than from trusting the sender not to repeat itself.
ALTER TABLE apps ADD COLUMN last_deployed_sha text NOT NULL DEFAULT '';

-- Finding the apps a push might affect, and the apps a poll should check.
-- Partial, because auto-deploy is off for most apps and the index should only
-- carry the ones it is asked about.
CREATE INDEX apps_auto_deploy_idx ON apps (owner_id) WHERE auto_deploy;

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP INDEX apps_auto_deploy_idx;
ALTER TABLE apps DROP COLUMN last_deployed_sha;
ALTER TABLE apps DROP COLUMN deploy_key_public;
ALTER TABLE apps DROP COLUMN deploy_key;
ALTER TABLE apps DROP COLUMN webhook_secret;
ALTER TABLE apps DROP COLUMN auto_deploy;
-- +goose StatementEnd
