package backup

import (
	"fmt"
	"strings"
)

// Image is what backup and restore tasks run.
//
// One image with restic and the Postgres client tools in it, pinned. Restic
// alone would not do: a Postgres backup is `pg_dump | restic backup --stdin`,
// and splitting that across two containers means the dump has to land
// somewhere in between — on a disk that would need to be as large as the
// database, in a pod that has no such disk.
//
// The tag is pinned rather than floating for the usual reason and one extra:
// restic's repository format is versioned, and a repository written by a newer
// restic cannot be read by an older one. An image that moves on its own can
// upgrade a repository in the night and leave every other install unable to
// restore from it.
const Image = "ghcr.io/kingzion24/ozymandis-backup:restic-0.18.0-pg16"

// The uid the backup image runs as. Non-root like everything else here, and
// the image is built with a user at this id owning the restic cache directory.
const (
	RunAsUser int64 = 65532
	FSGroup   int64 = 65532
)

// dataMount is where a volume being backed up is mounted inside the task.
//
// Fixed rather than reusing the app's own mount path, because the app's path is
// arbitrary and the script would have to be rewritten per app. The path a file
// is backed up *at* is what a restore writes it back to, so a fixed mount also
// means a volume restored into a differently configured app still lands
// correctly.
const dataMount = "/data"

// Env returns the environment every restic invocation needs.
//
// Split from Secrets deliberately: these are the values it is fine to see in a
// pod template, and the ones that are not are in Secrets.
func Env(d Destination, app string) map[string]string {
	return map[string]string{
		"RESTIC_REPOSITORY": d.Repository(app),
		"AWS_DEFAULT_REGION": func() string {
			if d.Region == "" {
				return "auto"
			}
			return d.Region
		}(),

		// Restic writes a cache to speed up subsequent runs. The root
		// filesystem is read-only and /tmp is the writable mount every task
		// gets, so it goes there — and being lost between runs costs a slower
		// backup, not a wrong one.
		"RESTIC_CACHE_DIR": "/tmp/restic-cache",
	}
}

// Secrets returns the values that must not appear in a pod template.
func Secrets(d Destination) map[string]string {
	return map[string]string{
		"AWS_ACCESS_KEY_ID":     d.AccessKeyID,
		"AWS_SECRET_ACCESS_KEY": d.SecretAccessKey,
		"RESTIC_PASSWORD":       d.RepoPassword,
	}
}

// PostgresSecrets adds the database password a dump needs.
func PostgresSecrets(d Destination, pgPassword string) map[string]string {
	s := Secrets(d)
	s["PGPASSWORD"] = pgPassword
	return s
}

// shellQuote renders a value safe to interpolate into a single-quoted shell
// word.
//
// Every value these scripts interpolate is generated by this engine rather than
// typed by a person — app names are DNS labels, tags are built from them. This
// is the backstop, not the protection: a script that is only safe because of a
// validation somewhere else is one that becomes unsafe when that validation
// moves.
func shellQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}

// tagArgs renders a target's tags as restic arguments.
func tagArgs(t Target) string {
	var b strings.Builder
	for _, tag := range t.Tags() {
		b.WriteString(" --tag " + shellQuote(tag))
	}
	return b.String()
}

// forgetArgs renders the retention policy.
func forgetArgs(p Policy) string {
	var parts []string
	if p.KeepDaily > 0 {
		parts = append(parts, fmt.Sprintf("--keep-daily %d", p.KeepDaily))
	}
	if p.KeepWeekly > 0 {
		parts = append(parts, fmt.Sprintf("--keep-weekly %d", p.KeepWeekly))
	}
	if p.KeepMonthly > 0 {
		parts = append(parts, fmt.Sprintf("--keep-monthly %d", p.KeepMonthly))
	}
	return strings.Join(parts, " ")
}

// preamble initialises the repository if it is not there yet.
//
// `restic init` on an existing repository fails, and `cat_config` succeeding is
// how you ask whether one exists without creating it. Doing this on every run
// rather than once at setup means an operator who empties the bucket gets a
// working backup that night instead of a job failing until somebody
// reinitialises by hand.
const preamble = `
set -eu

if ! restic cat config >/dev/null 2>&1; then
  echo "Initialising the repository at $RESTIC_REPOSITORY"
  restic init
fi
`

// BackupScript is the shell a backup task runs.
//
// One script per target rather than one that loops. A database and a volume
// fail in different ways and are restored by different commands, and a single
// job that did both would report one exit status for two questions — leaving
// "the backup failed" to mean either or both.
func BackupScript(p Policy, t Target) string {
	tags := tagArgs(t)
	forget := forgetArgs(p)

	var capture string
	switch t.Kind {
	case KindPostgres:
		// --clean and --if-exists so the dump can be restored over an existing
		// database, which is the only kind of database anybody restores onto.
		// Without them a restore into a live app fails on the first CREATE
		// TABLE and leaves the data half-replaced.
		//
		// The pipe is the point: nothing is written to disk in between, so a
		// backup of a database larger than the pod's ephemeral storage still
		// works. Postgres's own exit status is preserved by pipefail below.
		capture = fmt.Sprintf(`
echo "Dumping %s from %s"
pg_dump --clean --if-exists --no-owner --no-privileges \
  -h %s -p %d -U "$PGUSER" -d "$PGDATABASE" \
  | restic backup --stdin --stdin-filename dump.sql%s`,
			shellQuote(t.Name), shellQuote(t.Service),
			shellQuote(t.Service), t.Port, tags)

	case KindVolume:
		capture = fmt.Sprintf(`
echo "Backing up %s"
restic backup %s%s`, shellQuote(t.Name), dataMount, tags)
	}

	return preamble + `
# pipefail matters here and nowhere else in this script: without it a pg_dump
# that dies halfway is invisible, because restic exits zero having faithfully
# stored the truncated output. That is the failure that produces a backup which
# looks fine for months and restores into half a database.
set -o pipefail
` + capture + `

echo "Applying retention"
restic forget ` + forget + tags + ` --prune

echo "Done"
restic snapshots --compact` + tags
}

// RestoreScript is the shell a restore task runs.
//
// snapshot is a restic snapshot id, or "latest".
func RestoreScript(t Target, snapshot string) string {
	id := shellQuote(snapshot)
	tags := tagArgs(t)

	switch t.Kind {
	case KindPostgres:
		// Streamed straight into psql, for the same reason the dump was
		// streamed out: no intermediate file, so the restore is not bounded by
		// the pod's disk.
		//
		// ON_ERROR_STOP is what makes this report failure. Without it psql
		// prints errors, carries on to the next statement, and exits zero — so
		// a restore that dropped half the tables and failed to recreate them
		// would be reported as having worked.
		return preamble + `
set -o pipefail

echo "Restoring ` + shellQuote(t.Name) + ` from snapshot ` + id + `"
restic dump` + tags + ` ` + id + ` dump.sql \
  | psql -v ON_ERROR_STOP=1 -h ` + shellQuote(t.Service) +
			fmt.Sprintf(" -p %d", t.Port) + ` -U "$PGUSER" -d "$PGDATABASE"

echo "Restored"`

	case KindVolume:
		// --delete so the volume ends up as the snapshot describes it rather
		// than as the snapshot merged over whatever is there. A restore that
		// leaves files the snapshot does not contain is not a restore, and the
		// leftovers are exactly the corruption somebody is restoring to
		// escape.
		//
		// --include is what scopes that deletion, and restic refuses --delete
		// against / without one. It is right to: the flag means "remove
		// anything under the target that is not in the snapshot", and the
		// target here is the root of the task's own filesystem. The include
		// narrows it to the mounted claim, so the deletion can only reach the
		// volume being restored.
		return preamble + `
echo "Restoring ` + shellQuote(t.Name) + ` from snapshot ` + id + `"
restic restore` + tags + ` ` + id + ` --target / --include ` + dataMount + ` --delete

echo "Restored"`
	}

	return ""
}

// SnapshotsScript lists what the repository holds, as JSON.
//
// Asking restic rather than reading a table, because the repository is the only
// thing that knows what it actually contains. A row saying a snapshot exists is
// a claim; this is the answer.
func SnapshotsScript() string {
	return preamble + `
restic snapshots --json`
}

// MountPath is where a volume target is mounted in a backup or restore task.
func MountPath() string { return dataMount }
