// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countOwnersOfTeam = `-- name: CountOwnersOfTeam :one
SELECT count(*) FROM memberships WHERE owner_id = $1 AND role = 'owner'
`

func (q *Queries) CountOwnersOfTeam(ctx context.Context, ownerID string) (int64, error) {
	row := q.db.QueryRow(ctx, countOwnersOfTeam, ownerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSuperusers = `-- name: CountSuperusers :one
SELECT count(*) FROM users WHERE is_superuser
`

func (q *Queries) CountSuperusers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countSuperusers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (user_id, token_hash, active_team_id, user_agent, ip, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, token_hash, active_team_id, user_agent, ip, expires_at, created_at
`

type CreateSessionParams struct {
	UserID       uuid.UUID
	TokenHash    []byte
	ActiveTeamID *string
	UserAgent    string
	Ip           string
	ExpiresAt    time.Time
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.TokenHash,
		arg.ActiveTeamID,
		arg.UserAgent,
		arg.Ip,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ActiveTeamID,
		&i.UserAgent,
		&i.Ip,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createTeam = `-- name: CreateTeam :one
INSERT INTO teams (id, display_name)
VALUES ($1, $2)
ON CONFLICT (id) DO UPDATE SET display_name = excluded.display_name, updated_at = now()
RETURNING id, display_name, email, created_at, updated_at
`

type CreateTeamParams struct {
	ID          string
	DisplayName string
}

func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error) {
	row := q.db.QueryRow(ctx, createTeam, arg.ID, arg.DisplayName)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one

INSERT INTO users (username, password_hash, display_name, is_superuser)
VALUES (lower($1::text), $2, $3, $4)
RETURNING id, email, display_name, totp_secret, totp_confirmed, created_at, updated_at, username, password_hash, is_superuser
`

type CreateUserParams struct {
	Username     string
	PasswordHash []byte
	DisplayName  string
	IsSuperuser  bool
}

// Users and sessions carry no owner_id: a person exists before they belong to
// any team. Memberships do, and stay scoped by it like everything else.
//
// Sign-in is username and password. There is no query here that looks a person
// up by address, because an address no longer identifies anybody — it is a
// contact field, and the credential is the password hash.
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.PasswordHash,
		arg.DisplayName,
		arg.IsSuperuser,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.TotpSecret,
		&i.TotpConfirmed,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.PasswordHash,
		&i.IsSuperuser,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions)
	return err
}

const deleteMembership = `-- name: DeleteMembership :exec
DELETE FROM memberships WHERE user_id = $1 AND owner_id = $2
`

type DeleteMembershipParams struct {
	UserID  uuid.UUID
	OwnerID string
}

func (q *Queries) DeleteMembership(ctx context.Context, arg DeleteMembershipParams) error {
	_, err := q.db.Exec(ctx, deleteMembership, arg.UserID, arg.OwnerID)
	return err
}

const deleteSessionByHash = `-- name: DeleteSessionByHash :exec
DELETE FROM sessions WHERE token_hash = $1
`

func (q *Queries) DeleteSessionByHash(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, deleteSessionByHash, tokenHash)
	return err
}

const deleteSessionsForUser = `-- name: DeleteSessionsForUser :exec
DELETE FROM sessions WHERE user_id = $1
`

func (q *Queries) DeleteSessionsForUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSessionsForUser, userID)
	return err
}

const deleteUser = `-- name: DeleteUser :execrows
DELETE FROM users WHERE id = $1 AND NOT is_superuser
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const ensureSuperuser = `-- name: EnsureSuperuser :one
INSERT INTO users (username, password_hash, display_name, is_superuser)
VALUES (lower($1::text), $2, $3, true)
ON CONFLICT (lower(username)) DO UPDATE
SET is_superuser = true,
    updated_at   = now()
RETURNING id, email, display_name, totp_secret, totp_confirmed, created_at, updated_at, username, password_hash, is_superuser
`

type EnsureSuperuserParams struct {
	Username     string
	PasswordHash []byte
	DisplayName  string
}

// Seeding the superuser is an upsert on the name, and it deliberately does not
// touch password_hash. Re-running the process must not put the built-in default
// back over a password somebody has since changed — that would make every
// restart a silent credential reset.
func (q *Queries) EnsureSuperuser(ctx context.Context, arg EnsureSuperuserParams) (User, error) {
	row := q.db.QueryRow(ctx, ensureSuperuser, arg.Username, arg.PasswordHash, arg.DisplayName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.TotpSecret,
		&i.TotpConfirmed,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.PasswordHash,
		&i.IsSuperuser,
	)
	return i, err
}

const getMembership = `-- name: GetMembership :one
SELECT user_id, owner_id, role, created_at FROM memberships WHERE user_id = $1 AND owner_id = $2
`

type GetMembershipParams struct {
	UserID  uuid.UUID
	OwnerID string
}

func (q *Queries) GetMembership(ctx context.Context, arg GetMembershipParams) (Membership, error) {
	row := q.db.QueryRow(ctx, getMembership, arg.UserID, arg.OwnerID)
	var i Membership
	err := row.Scan(
		&i.UserID,
		&i.OwnerID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT id, user_id, token_hash, active_team_id, user_agent, ip, expires_at, created_at FROM sessions WHERE id = $1
`

func (q *Queries) GetSession(ctx context.Context, id uuid.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ActiveTeamID,
		&i.UserAgent,
		&i.Ip,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSessionByHash = `-- name: GetSessionByHash :one
SELECT s.id, s.user_id, s.token_hash, s.active_team_id, s.user_agent, s.ip, s.expires_at, s.created_at, t.display_name AS team_name, t.email AS team_email, m.role AS member_role
FROM sessions s
JOIN teams t ON t.id = s.active_team_id
JOIN memberships m ON m.owner_id = s.active_team_id AND m.user_id = s.user_id
WHERE s.token_hash = $1 AND s.expires_at > now()
`

type GetSessionByHashRow struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	TokenHash    []byte
	ActiveTeamID *string
	UserAgent    string
	Ip           string
	ExpiresAt    time.Time
	CreatedAt    time.Time
	TeamName     string
	TeamEmail    string
	MemberRole   string
}

// The team is joined in because the request that carries this cookie needs the
// owner it resolves to, and a second round trip per request buys nothing. The
// join is LEFT: a session whose team was deleted still exists, it just has no
// owner to act as.
//
// Expiry is filtered in SQL rather than in Go so that an expired row can never
// be treated as valid by a caller that forgets to check.
// Resolves a session only while the membership behind it still exists.
//
// The join to memberships is the security boundary, not decoration. Revoking
// sessions imperatively when someone is removed would work only for the call
// sites that remember to do it, and would still miss membership lost by
// cascade. Joining makes a departed member's cookie stop resolving the instant
// the row goes, by whatever route it went.
//
// INNER JOIN on teams too: a session with no active team resolves to no owner,
// and returning a row the caller must then remember to reject is how that
// check gets skipped.
func (q *Queries) GetSessionByHash(ctx context.Context, tokenHash []byte) (GetSessionByHashRow, error) {
	row := q.db.QueryRow(ctx, getSessionByHash, tokenHash)
	var i GetSessionByHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ActiveTeamID,
		&i.UserAgent,
		&i.Ip,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.TeamName,
		&i.TeamEmail,
		&i.MemberRole,
	)
	return i, err
}

const getTeam = `-- name: GetTeam :one
SELECT id, display_name, email, created_at, updated_at FROM teams WHERE id = $1
`

func (q *Queries) GetTeam(ctx context.Context, id string) (Team, error) {
	row := q.db.QueryRow(ctx, getTeam, id)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, display_name, totp_secret, totp_confirmed, created_at, updated_at, username, password_hash, is_superuser FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.TotpSecret,
		&i.TotpConfirmed,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.PasswordHash,
		&i.IsSuperuser,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, email, display_name, totp_secret, totp_confirmed, created_at, updated_at, username, password_hash, is_superuser FROM users WHERE lower(username) = lower($1::text)
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.TotpSecret,
		&i.TotpConfirmed,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.PasswordHash,
		&i.IsSuperuser,
	)
	return i, err
}

const listMembersOfTeam = `-- name: ListMembersOfTeam :many
SELECT m.user_id, m.owner_id, m.role, m.created_at, u.username, u.display_name AS user_name
FROM memberships m
JOIN users u ON u.id = m.user_id
WHERE m.owner_id = $1
ORDER BY lower(u.username)
`

type ListMembersOfTeamRow struct {
	UserID    uuid.UUID
	OwnerID   string
	Role      string
	CreatedAt time.Time
	Username  string
	UserName  string
}

func (q *Queries) ListMembersOfTeam(ctx context.Context, ownerID string) ([]ListMembersOfTeamRow, error) {
	rows, err := q.db.Query(ctx, listMembersOfTeam, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMembersOfTeamRow{}
	for rows.Next() {
		var i ListMembersOfTeamRow
		if err := rows.Scan(
			&i.UserID,
			&i.OwnerID,
			&i.Role,
			&i.CreatedAt,
			&i.Username,
			&i.UserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembershipsForUser = `-- name: ListMembershipsForUser :many
SELECT m.user_id, m.owner_id, m.role, m.created_at, t.display_name AS team_name
FROM memberships m
JOIN teams t ON t.id = m.owner_id
WHERE m.user_id = $1
ORDER BY t.display_name
`

type ListMembershipsForUserRow struct {
	UserID    uuid.UUID
	OwnerID   string
	Role      string
	CreatedAt time.Time
	TeamName  string
}

func (q *Queries) ListMembershipsForUser(ctx context.Context, userID uuid.UUID) ([]ListMembershipsForUserRow, error) {
	rows, err := q.db.Query(ctx, listMembershipsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMembershipsForUserRow{}
	for rows.Next() {
		var i ListMembershipsForUserRow
		if err := rows.Scan(
			&i.UserID,
			&i.OwnerID,
			&i.Role,
			&i.CreatedAt,
			&i.TeamName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, display_name, totp_secret, totp_confirmed, created_at, updated_at, username, password_hash, is_superuser FROM users ORDER BY is_superuser DESC, lower(username)
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.DisplayName,
			&i.TotpSecret,
			&i.TotpConfirmed,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Username,
			&i.PasswordHash,
			&i.IsSuperuser,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockTeam = `-- name: LockTeam :one
SELECT id, display_name, email, created_at, updated_at FROM teams WHERE id = $1 FOR UPDATE
`

// A role change reads the owner count and then writes; taking the team row
// first serialises those pairs, so two concurrent demotions cannot both see
// two owners and both proceed.
func (q *Queries) LockTeam(ctx context.Context, id string) (Team, error) {
	row := q.db.QueryRow(ctx, lockTeam, id)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setSessionTeam = `-- name: SetSessionTeam :exec
UPDATE sessions SET active_team_id = $1 WHERE id = $2
`

type SetSessionTeamParams struct {
	ActiveTeamID *string
	ID           uuid.UUID
}

func (q *Queries) SetSessionTeam(ctx context.Context, arg SetSessionTeamParams) error {
	_, err := q.db.Exec(ctx, setSessionTeam, arg.ActiveTeamID, arg.ID)
	return err
}

const setUserPassword = `-- name: SetUserPassword :exec
UPDATE users SET password_hash = $1, updated_at = now() WHERE id = $2
`

type SetUserPasswordParams struct {
	PasswordHash []byte
	ID           uuid.UUID
}

func (q *Queries) SetUserPassword(ctx context.Context, arg SetUserPasswordParams) error {
	_, err := q.db.Exec(ctx, setUserPassword, arg.PasswordHash, arg.ID)
	return err
}

const upsertMembership = `-- name: UpsertMembership :one
INSERT INTO memberships (user_id, owner_id, role)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, owner_id) DO UPDATE SET role = excluded.role
RETURNING user_id, owner_id, role, created_at
`

type UpsertMembershipParams struct {
	UserID  uuid.UUID
	OwnerID string
	Role    string
}

func (q *Queries) UpsertMembership(ctx context.Context, arg UpsertMembershipParams) (Membership, error) {
	row := q.db.QueryRow(ctx, upsertMembership, arg.UserID, arg.OwnerID, arg.Role)
	var i Membership
	err := row.Scan(
		&i.UserID,
		&i.OwnerID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}
