// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_tokens.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAPIToken = `-- name: CreateAPIToken :one
INSERT INTO api_tokens (user_id, owner_id, name, token_hash, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, owner_id, name, token_hash, last_used_at, expires_at, created_at
`

type CreateAPITokenParams struct {
	UserID    uuid.UUID
	OwnerID   string
	Name      string
	TokenHash []byte
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateAPIToken(ctx context.Context, arg CreateAPITokenParams) (ApiToken, error) {
	row := q.db.QueryRow(ctx, createAPIToken,
		arg.UserID,
		arg.OwnerID,
		arg.Name,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OwnerID,
		&i.Name,
		&i.TokenHash,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAPIToken = `-- name: DeleteAPIToken :exec
DELETE FROM api_tokens
WHERE id = $1 AND user_id = $2 AND owner_id = $3
`

type DeleteAPITokenParams struct {
	ID      uuid.UUID
	UserID  uuid.UUID
	OwnerID string
}

// Deleted by id, scoped by user and team so that holding an id from somewhere
// else is not enough to revoke somebody's credential.
func (q *Queries) DeleteAPIToken(ctx context.Context, arg DeleteAPITokenParams) error {
	_, err := q.db.Exec(ctx, deleteAPIToken, arg.ID, arg.UserID, arg.OwnerID)
	return err
}

const deleteExpiredAPITokens = `-- name: DeleteExpiredAPITokens :exec
DELETE FROM api_tokens WHERE expires_at IS NOT NULL AND expires_at <= now()
`

func (q *Queries) DeleteExpiredAPITokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredAPITokens)
	return err
}

const getAPITokenByHash = `-- name: GetAPITokenByHash :one
SELECT t.id, t.user_id, t.owner_id, t.name, t.token_hash, t.last_used_at, t.expires_at, t.created_at, u.email AS user_email, u.display_name AS user_name,
       m.role AS member_role, tm.display_name AS team_name, tm.email AS team_email
FROM api_tokens t
JOIN users u ON u.id = t.user_id
JOIN teams tm ON tm.id = t.owner_id
JOIN memberships m ON m.owner_id = t.owner_id AND m.user_id = t.user_id
WHERE t.token_hash = $1
  AND (t.expires_at IS NULL OR t.expires_at > now())
`

type GetAPITokenByHashRow struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	OwnerID    string
	Name       string
	TokenHash  []byte
	LastUsedAt pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
	CreatedAt  time.Time
	UserEmail  string
	UserName   string
	MemberRole string
	TeamName   string
	TeamEmail  string
}

// Resolves a token only while the membership behind it still exists, and
// returns the role in the same row.
//
// This is GetSessionByHash with a different credential, and it is deliberately
// the same shape in all three respects that matter:
//
// The join to memberships is the security boundary, not decoration. A token
// outlives the browser that minted it by design, so "revoke the credential when
// someone leaves" is a step that will be missed — here it cannot be, because a
// departed member's token stops resolving the instant the membership row goes,
// by whatever route it went, including cascade.
//
// The row is deleted by that same cascade rather than merely orphaned; the
// schema carries a composite foreign key onto memberships to ensure it. This
// join is therefore defence in depth rather than the whole mechanism, which is
// the right way round: were it the only mechanism, removing somebody would
// suspend their tokens rather than revoke them, and re-adding them would bring
// every one of those credentials back.
//
// The role comes back with the credential because the query that proves the
// token is live is the query that says what it may do. Looking the role up
// separately gives two answers that can disagree, and the window between them
// is the one where a demoted member still writes.
//
// Expiry is filtered in SQL rather than in Go so that an expired row can never
// be treated as valid by a caller that forgets to check. NULL means no expiry,
// which is the common case for a credential living in CI.
func (q *Queries) GetAPITokenByHash(ctx context.Context, tokenHash []byte) (GetAPITokenByHashRow, error) {
	row := q.db.QueryRow(ctx, getAPITokenByHash, tokenHash)
	var i GetAPITokenByHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OwnerID,
		&i.Name,
		&i.TokenHash,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UserEmail,
		&i.UserName,
		&i.MemberRole,
		&i.TeamName,
		&i.TeamEmail,
	)
	return i, err
}

const listAPITokens = `-- name: ListAPITokens :many
SELECT id, user_id, owner_id, name, token_hash, last_used_at, expires_at, created_at FROM api_tokens
WHERE user_id = $1 AND owner_id = $2
ORDER BY created_at DESC
`

type ListAPITokensParams struct {
	UserID  uuid.UUID
	OwnerID string
}

// The list a person prunes from. Scoped by both user and team: a token is a
// credential of one person acting as one team, and listing another person's is
// neither useful nor theirs to see.
func (q *Queries) ListAPITokens(ctx context.Context, arg ListAPITokensParams) ([]ApiToken, error) {
	rows, err := q.db.Query(ctx, listAPITokens, arg.UserID, arg.OwnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiToken{}
	for rows.Next() {
		var i ApiToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.OwnerID,
			&i.Name,
			&i.TokenHash,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchAPIToken = `-- name: TouchAPIToken :exec
UPDATE api_tokens SET last_used_at = now() WHERE id = $1
`

// Best-effort bookkeeping on a hot path. Separate from GetAPITokenByHash rather
// than folded into it with a CTE: resolving a credential is a read, and making
// it a write puts every authenticated API request into a row lock on the same
// token. A CI job running twenty parallel deploys would serialise on it.
func (q *Queries) TouchAPIToken(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchAPIToken, id)
	return err
}
