// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: builds.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

const appendBuildLog = `-- name: AppendBuildLog :exec
UPDATE builds
SET log = log || $1::text
WHERE id = $2
`

type AppendBuildLogParams struct {
	Chunk string
	ID    uuid.UUID
}

// Appended rather than replaced, so a build streaming its output does not have
// to hold the whole log in memory to write any of it.
func (q *Queries) AppendBuildLog(ctx context.Context, arg AppendBuildLogParams) error {
	_, err := q.db.Exec(ctx, appendBuildLog, arg.Chunk, arg.ID)
	return err
}

const createBuild = `-- name: CreateBuild :one

INSERT INTO builds (owner_id, app_id, deployment_id, repo_url, repo_ref)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, owner_id, app_id, deployment_id, repo_url, repo_ref, commit_sha, image, status, message, log, started_at, finished_at, job_name
`

type CreateBuildParams struct {
	OwnerID      string
	AppID        uuid.UUID
	DeploymentID uuid.UUID
	RepoUrl      string
	RepoRef      string
}

// Builds. Owner-scoped in the row rather than through the deployment, because
// the log is readable output and the scoping has to be checkable in the query
// that reads it.
func (q *Queries) CreateBuild(ctx context.Context, arg CreateBuildParams) (Build, error) {
	row := q.db.QueryRow(ctx, createBuild,
		arg.OwnerID,
		arg.AppID,
		arg.DeploymentID,
		arg.RepoUrl,
		arg.RepoRef,
	)
	var i Build
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.AppID,
		&i.DeploymentID,
		&i.RepoUrl,
		&i.RepoRef,
		&i.CommitSha,
		&i.Image,
		&i.Status,
		&i.Message,
		&i.Log,
		&i.StartedAt,
		&i.FinishedAt,
		&i.JobName,
	)
	return i, err
}

const finishBuild = `-- name: FinishBuild :one
UPDATE builds
SET status      = $1,
    message     = $2,
    image       = $3,
    commit_sha  = $4,
    finished_at = now()
WHERE id = $5 AND status = 'running'
RETURNING id, owner_id, app_id, deployment_id, repo_url, repo_ref, commit_sha, image, status, message, log, started_at, finished_at, job_name
`

type FinishBuildParams struct {
	Status    string
	Message   string
	Image     string
	CommitSha string
	ID        uuid.UUID
}

// Only a build still running can be finished. Two things write this — the
// goroutine that ran the build and the reconciler settling one whose process
// went away — and without the guard the second overwrote the first: a build
// the reconciler had failed, along with its deployment, was rewritten to
// succeeded a moment later and left a succeeded build under a failed deploy.
// Whoever arrives second gets no row and knows it lost.
func (q *Queries) FinishBuild(ctx context.Context, arg FinishBuildParams) (Build, error) {
	row := q.db.QueryRow(ctx, finishBuild,
		arg.Status,
		arg.Message,
		arg.Image,
		arg.CommitSha,
		arg.ID,
	)
	var i Build
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.AppID,
		&i.DeploymentID,
		&i.RepoUrl,
		&i.RepoRef,
		&i.CommitSha,
		&i.Image,
		&i.Status,
		&i.Message,
		&i.Log,
		&i.StartedAt,
		&i.FinishedAt,
		&i.JobName,
	)
	return i, err
}

const getBuild = `-- name: GetBuild :one
SELECT id, owner_id, app_id, deployment_id, repo_url, repo_ref, commit_sha, image, status, message, log, started_at, finished_at, job_name FROM builds
WHERE owner_id = $1 AND id = $2
`

type GetBuildParams struct {
	OwnerID string
	ID      uuid.UUID
}

func (q *Queries) GetBuild(ctx context.Context, arg GetBuildParams) (Build, error) {
	row := q.db.QueryRow(ctx, getBuild, arg.OwnerID, arg.ID)
	var i Build
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.AppID,
		&i.DeploymentID,
		&i.RepoUrl,
		&i.RepoRef,
		&i.CommitSha,
		&i.Image,
		&i.Status,
		&i.Message,
		&i.Log,
		&i.StartedAt,
		&i.FinishedAt,
		&i.JobName,
	)
	return i, err
}

const getBuildForDeployment = `-- name: GetBuildForDeployment :one
SELECT id, owner_id, app_id, deployment_id, repo_url, repo_ref, commit_sha, image, status, message, log, started_at, finished_at, job_name FROM builds
WHERE owner_id = $1 AND deployment_id = $2
`

type GetBuildForDeploymentParams struct {
	OwnerID      string
	DeploymentID uuid.UUID
}

func (q *Queries) GetBuildForDeployment(ctx context.Context, arg GetBuildForDeploymentParams) (Build, error) {
	row := q.db.QueryRow(ctx, getBuildForDeployment, arg.OwnerID, arg.DeploymentID)
	var i Build
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.AppID,
		&i.DeploymentID,
		&i.RepoUrl,
		&i.RepoRef,
		&i.CommitSha,
		&i.Image,
		&i.Status,
		&i.Message,
		&i.Log,
		&i.StartedAt,
		&i.FinishedAt,
		&i.JobName,
	)
	return i, err
}

const listRunningBuilds = `-- name: ListRunningBuilds :many
SELECT id, owner_id, app_id, deployment_id, repo_url, repo_ref, commit_sha, image, status, message, log, started_at, finished_at, job_name FROM builds WHERE status = 'running' ORDER BY started_at
`

// Every build still claiming to run, oldest first. Not owner-scoped: this
// feeds the reconciler, which is the platform settling its own records rather
// than a team reading theirs.
func (q *Queries) ListRunningBuilds(ctx context.Context) ([]Build, error) {
	rows, err := q.db.Query(ctx, listRunningBuilds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Build{}
	for rows.Next() {
		var i Build
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.AppID,
			&i.DeploymentID,
			&i.RepoUrl,
			&i.RepoRef,
			&i.CommitSha,
			&i.Image,
			&i.Status,
			&i.Message,
			&i.Log,
			&i.StartedAt,
			&i.FinishedAt,
			&i.JobName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setBuildJob = `-- name: SetBuildJob :exec
UPDATE builds SET job_name = $1 WHERE id = $2
`

type SetBuildJobParams struct {
	JobName string
	ID      uuid.UUID
}

func (q *Queries) SetBuildJob(ctx context.Context, arg SetBuildJobParams) error {
	_, err := q.db.Exec(ctx, setBuildJob, arg.JobName, arg.ID)
	return err
}
