// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: domains.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

const createCustomDomain = `-- name: CreateCustomDomain :one

INSERT INTO domains (owner_id, app_id, host, tls, verified, managed, verify_target)
VALUES ($1, $2, lower($3), true, false, false, $4)
RETURNING id, owner_id, app_id, host, tls, verified, created_at, managed, verified_at, verify_target
`

type CreateCustomDomainParams struct {
	OwnerID      string
	AppID        uuid.UUID
	Host         string
	VerifyTarget string
}

// ---------------------------------------------------------- custom domains
// Claims a hostname for an app, unverified.
//
// Deliberately not an upsert on host: the global unique index is what makes two
// teams claiming one name an error rather than a silent transfer, and papering
// over it here is exactly how a domain gets stolen.
func (q *Queries) CreateCustomDomain(ctx context.Context, arg CreateCustomDomainParams) (Domain, error) {
	row := q.db.QueryRow(ctx, createCustomDomain,
		arg.OwnerID,
		arg.AppID,
		arg.Host,
		arg.VerifyTarget,
	)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.AppID,
		&i.Host,
		&i.Tls,
		&i.Verified,
		&i.CreatedAt,
		&i.Managed,
		&i.VerifiedAt,
		&i.VerifyTarget,
	)
	return i, err
}

const deleteCustomDomain = `-- name: DeleteCustomDomain :execrows
DELETE FROM domains
WHERE owner_id = $1 AND id = $2 AND NOT managed
`

type DeleteCustomDomainParams struct {
	OwnerID string
	ID      uuid.UUID
}

func (q *Queries) DeleteCustomDomain(ctx context.Context, arg DeleteCustomDomainParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCustomDomain, arg.OwnerID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteManagedDomain = `-- name: DeleteManagedDomain :exec
DELETE FROM domains
WHERE app_id = $1 AND managed
`

// Releases an app's platform hostname.
//
// Deleting rather than leaving the row is what makes the feature reversible:
// hostnames are globally unique, so a retired row keeps the name reserved
// against every other app forever.
func (q *Queries) DeleteManagedDomain(ctx context.Context, appID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteManagedDomain, appID)
	return err
}

const getCustomDomain = `-- name: GetCustomDomain :one
SELECT id, owner_id, app_id, host, tls, verified, created_at, managed, verified_at, verify_target FROM domains
WHERE owner_id = $1 AND id = $2 AND NOT managed
`

type GetCustomDomainParams struct {
	OwnerID string
	ID      uuid.UUID
}

func (q *Queries) GetCustomDomain(ctx context.Context, arg GetCustomDomainParams) (Domain, error) {
	row := q.db.QueryRow(ctx, getCustomDomain, arg.OwnerID, arg.ID)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.AppID,
		&i.Host,
		&i.Tls,
		&i.Verified,
		&i.CreatedAt,
		&i.Managed,
		&i.VerifiedAt,
		&i.VerifyTarget,
	)
	return i, err
}

const getManagedDomain = `-- name: GetManagedDomain :one
SELECT id, owner_id, app_id, host, tls, verified, created_at, managed, verified_at, verify_target FROM domains
WHERE app_id = $1 AND managed
LIMIT 1
`

func (q *Queries) GetManagedDomain(ctx context.Context, appID uuid.UUID) (Domain, error) {
	row := q.db.QueryRow(ctx, getManagedDomain, appID)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.AppID,
		&i.Host,
		&i.Tls,
		&i.Verified,
		&i.CreatedAt,
		&i.Managed,
		&i.VerifiedAt,
		&i.VerifyTarget,
	)
	return i, err
}

const listCustomDomains = `-- name: ListCustomDomains :many
SELECT id, owner_id, app_id, host, tls, verified, created_at, managed, verified_at, verify_target FROM domains
WHERE owner_id = $1 AND app_id = $2 AND NOT managed
ORDER BY host
`

type ListCustomDomainsParams struct {
	OwnerID string
	AppID   uuid.UUID
}

func (q *Queries) ListCustomDomains(ctx context.Context, arg ListCustomDomainsParams) ([]Domain, error) {
	rows, err := q.db.Query(ctx, listCustomDomains, arg.OwnerID, arg.AppID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Domain{}
	for rows.Next() {
		var i Domain
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.AppID,
			&i.Host,
			&i.Tls,
			&i.Verified,
			&i.CreatedAt,
			&i.Managed,
			&i.VerifiedAt,
			&i.VerifyTarget,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDomainsByApp = `-- name: ListDomainsByApp :many
SELECT id, owner_id, app_id, host, tls, verified, created_at, managed, verified_at, verify_target FROM domains
WHERE app_id = $1
ORDER BY managed DESC, host
`

func (q *Queries) ListDomainsByApp(ctx context.Context, appID uuid.UUID) ([]Domain, error) {
	rows, err := q.db.Query(ctx, listDomainsByApp, appID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Domain{}
	for rows.Next() {
		var i Domain
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.AppID,
			&i.Host,
			&i.Tls,
			&i.Verified,
			&i.CreatedAt,
			&i.Managed,
			&i.VerifiedAt,
			&i.VerifyTarget,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const routableHostsForApp = `-- name: RoutableHostsForApp :many
SELECT host, managed FROM domains
WHERE app_id = $1 AND (managed OR verified)
ORDER BY managed DESC, host
`

type RoutableHostsForAppRow struct {
	Host    string
	Managed bool
}

// Hostnames that may actually be routed to, and whether the platform issued
// each one.
//
// A managed host is routable because the platform issued it; a custom one only
// once it is proven. This is the query the Ingress is built from, so the gate
// lives here rather than in a caller that might forget it.
//
// managed comes back with the host because it decides which certificate serves
// the name, and it is the recorded fact rather than a suffix comparison — see
// 00002. A caller that had only the hostname would have to re-derive it from
// the current app domain, which is the derivation that column exists to avoid.
func (q *Queries) RoutableHostsForApp(ctx context.Context, appID uuid.UUID) ([]RoutableHostsForAppRow, error) {
	rows, err := q.db.Query(ctx, routableHostsForApp, appID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RoutableHostsForAppRow{}
	for rows.Next() {
		var i RoutableHostsForAppRow
		if err := rows.Scan(&i.Host, &i.Managed); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertManagedDomain = `-- name: UpsertManagedDomain :one

INSERT INTO domains (owner_id, app_id, host, tls, verified, managed)
VALUES ($1, $2, lower($3), $4, true, true)
ON CONFLICT (app_id) WHERE managed
DO UPDATE SET host = lower($3), tls = $4
RETURNING id, owner_id, app_id, host, tls, verified, created_at, managed, verified_at, verify_target
`

type UpsertManagedDomainParams struct {
	OwnerID string
	AppID   uuid.UUID
	Host    string
	Tls     bool
}

// Platform-issued hostnames. Custom domains get their own queries when that
// sub-project lands; keeping them in one file rather than in apps.sql is so
// that apps.sql stays about apps.
// Issues or reissues the platform hostname for an app.
//
// The conflict target is the partial index, so a second call for the same app
// moves its hostname rather than adding one. A collision on the global host
// index is a different conflict and is deliberately left to raise, because two
// apps claiming one hostname is a real error, not something to paper over.
//
// verified is true because a name the platform issued needs no proof of
// ownership; requiring proof would mean inventing a verification step for a
// name we already control.
func (q *Queries) UpsertManagedDomain(ctx context.Context, arg UpsertManagedDomainParams) (Domain, error) {
	row := q.db.QueryRow(ctx, upsertManagedDomain,
		arg.OwnerID,
		arg.AppID,
		arg.Host,
		arg.Tls,
	)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.AppID,
		&i.Host,
		&i.Tls,
		&i.Verified,
		&i.CreatedAt,
		&i.Managed,
		&i.VerifiedAt,
		&i.VerifyTarget,
	)
	return i, err
}

const verifyCustomDomain = `-- name: VerifyCustomDomain :execrows
UPDATE domains
SET verified = true, verified_at = now()
WHERE owner_id = $1 AND id = $2 AND NOT managed
`

type VerifyCustomDomainParams struct {
	OwnerID string
	ID      uuid.UUID
}

// Marks a claim proven. Scoped by owner as well as id: verifying is a write,
// and a write on somebody else's row is the thing owner scoping exists for.
func (q *Queries) VerifyCustomDomain(ctx context.Context, arg VerifyCustomDomainParams) (int64, error) {
	result, err := q.db.Exec(ctx, verifyCustomDomain, arg.OwnerID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
