// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: exec_sessions.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const endExecSession = `-- name: EndExecSession :exec
UPDATE exec_sessions
SET ended_at  = now(),
    outcome   = $1,
    exit_code = $2
WHERE owner_id = $3 AND id = $4
`

type EndExecSessionParams struct {
	Outcome  string
	ExitCode *int32
	OwnerID  string
	ID       uuid.UUID
}

// Written on a detached, bounded context at teardown.
//
// Scoped by owner as well as id: an audit row is not something a caller should
// be able to close on somebody else's behalf by holding an id.
func (q *Queries) EndExecSession(ctx context.Context, arg EndExecSessionParams) error {
	_, err := q.db.Exec(ctx, endExecSession,
		arg.Outcome,
		arg.ExitCode,
		arg.OwnerID,
		arg.ID,
	)
	return err
}

const listExecSessions = `-- name: ListExecSessions :many
SELECT s.id, s.owner_id, s.app_id, s.actor, s.pod, s.command, s.tty, s.started_at, s.ended_at, s.outcome, s.exit_code, a.name AS app_name
FROM exec_sessions s
JOIN apps a ON a.id = s.app_id AND a.owner_id = s.owner_id
WHERE s.owner_id = $1
ORDER BY s.started_at DESC
LIMIT $2
`

type ListExecSessionsParams struct {
	OwnerID  string
	RowLimit int32
}

type ListExecSessionsRow struct {
	ID        uuid.UUID
	OwnerID   string
	AppID     uuid.UUID
	Actor     string
	Pod       string
	Command   string
	Tty       bool
	StartedAt time.Time
	EndedAt   pgtype.Timestamptz
	Outcome   string
	ExitCode  *int32
	AppName   string
}

func (q *Queries) ListExecSessions(ctx context.Context, arg ListExecSessionsParams) ([]ListExecSessionsRow, error) {
	rows, err := q.db.Query(ctx, listExecSessions, arg.OwnerID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExecSessionsRow{}
	for rows.Next() {
		var i ListExecSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.AppID,
			&i.Actor,
			&i.Pod,
			&i.Command,
			&i.Tty,
			&i.StartedAt,
			&i.EndedAt,
			&i.Outcome,
			&i.ExitCode,
			&i.AppName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenExecSessions = `-- name: ListOpenExecSessions :many
SELECT s.id, s.owner_id, s.app_id, s.actor, s.pod, s.command, s.tty, s.started_at, s.ended_at, s.outcome, s.exit_code, a.name AS app_name
FROM exec_sessions s
JOIN apps a ON a.id = s.app_id AND a.owner_id = s.owner_id
WHERE s.owner_id = $1 AND s.ended_at IS NULL
ORDER BY s.started_at DESC
`

type ListOpenExecSessionsRow struct {
	ID        uuid.UUID
	OwnerID   string
	AppID     uuid.UUID
	Actor     string
	Pod       string
	Command   string
	Tty       bool
	StartedAt time.Time
	EndedAt   pgtype.Timestamptz
	Outcome   string
	ExitCode  *int32
	AppName   string
}

// The sessions that have not ended.
//
// The signal this table exists to carry, and it needs a query or it is a signal
// nobody can read. Two different situations land here and both are worth
// seeing:
//
//   - somebody is in a container RIGHT NOW, which is what an incident asks
//   - a session ended in a way this process never observed — it was killed
//     with the process, or the machine went away — so nothing ever closed it
//
// They are deliberately not distinguished, because nothing observed the
// difference. A row that has been open for four seconds is somebody working; a
// row open for four days is a session nobody will ever account for, and the
// started_at is what tells them apart.
//
// Backed by the partial index on (owner_id) WHERE ended_at IS NULL.
func (q *Queries) ListOpenExecSessions(ctx context.Context, ownerID string) ([]ListOpenExecSessionsRow, error) {
	rows, err := q.db.Query(ctx, listOpenExecSessions, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOpenExecSessionsRow{}
	for rows.Next() {
		var i ListOpenExecSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.AppID,
			&i.Actor,
			&i.Pod,
			&i.Command,
			&i.Tty,
			&i.StartedAt,
			&i.EndedAt,
			&i.Outcome,
			&i.ExitCode,
			&i.AppName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const startExecSession = `-- name: StartExecSession :one
INSERT INTO exec_sessions (owner_id, app_id, actor, pod, command, tty)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, owner_id, app_id, actor, pod, command, tty, started_at, ended_at, outcome, exit_code
`

type StartExecSessionParams struct {
	OwnerID string
	AppID   uuid.UUID
	Actor   string
	Pod     string
	Command string
	Tty     bool
}

// Written BEFORE the stream opens, so a session that dies during attach has
// already been recorded. See 00025 for why the ordering is load-bearing.
func (q *Queries) StartExecSession(ctx context.Context, arg StartExecSessionParams) (ExecSession, error) {
	row := q.db.QueryRow(ctx, startExecSession,
		arg.OwnerID,
		arg.AppID,
		arg.Actor,
		arg.Pod,
		arg.Command,
		arg.Tty,
	)
	var i ExecSession
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.AppID,
		&i.Actor,
		&i.Pod,
		&i.Command,
		&i.Tty,
		&i.StartedAt,
		&i.EndedAt,
		&i.Outcome,
		&i.ExitCode,
	)
	return i, err
}
