// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiToken struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	OwnerID    string
	Name       string
	TokenHash  []byte
	LastUsedAt pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
	CreatedAt  time.Time
}

type App struct {
	ID              uuid.UUID
	OwnerID         string
	Name            string
	Namespace       string
	Image           string
	Replicas        int32
	Port            int32
	CpuRequest      string
	CpuLimit        string
	MemoryRequest   string
	MemoryLimit     string
	CreatedAt       time.Time
	UpdatedAt       time.Time
	HealthPath      string
	HealthLiveness  bool
	Source          string
	Internal        bool
	ProjectID       pgtype.UUID
	CanvasX         *int32
	CanvasY         *int32
	HttpsOnly       bool
	CnameOnly       bool
	RepoUrl         string
	RepoBranch      string
	RepoSubdir      string
	RunAsUser       int64
	Command         string
	ReleaseCommand  string
	AutoDeploy      bool
	WebhookSecret   []byte
	DeployKey       []byte
	DeployKeyPublic string
	LastDeployedSha string
}

type AppLink struct {
	OwnerID   string
	FromAppID uuid.UUID
	ToAppID   uuid.UUID
	ViaKey    string
	CreatedAt time.Time
}

type BackupDestination struct {
	OwnerID         string
	Endpoint        string
	Bucket          string
	Prefix          string
	Region          string
	AccessKeyID     string
	SecretAccessKey []byte
	RepoPassword    []byte
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type BackupPolicy struct {
	ID          uuid.UUID
	OwnerID     string
	AppID       uuid.UUID
	Enabled     bool
	Schedule    string
	KeepDaily   int32
	KeepWeekly  int32
	KeepMonthly int32
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Build struct {
	ID           uuid.UUID
	OwnerID      string
	AppID        uuid.UUID
	DeploymentID uuid.UUID
	RepoUrl      string
	RepoRef      string
	CommitSha    string
	Image        string
	Status       string
	Message      string
	Log          string
	StartedAt    time.Time
	FinishedAt   pgtype.Timestamptz
	JobName      string
}

type ClusterJoin struct {
	ID          int32
	ServerUrl   string
	TokenSealed []byte
	UpdatedAt   time.Time
	UpdatedBy   pgtype.UUID
}

type Deployment struct {
	ID            uuid.UUID
	OwnerID       string
	AppID         uuid.UUID
	Image         string
	Revision      string
	Status        string
	Message       string
	StartedAt     time.Time
	FinishedAt    pgtype.Timestamptz
	ReleaseLog    string
	ReleaseStatus string
}

type Domain struct {
	ID           uuid.UUID
	OwnerID      string
	AppID        uuid.UUID
	Host         string
	Tls          bool
	Verified     bool
	CreatedAt    time.Time
	Managed      bool
	VerifiedAt   pgtype.Timestamptz
	VerifyTarget string
}

type ExecSession struct {
	ID        uuid.UUID
	OwnerID   string
	AppID     uuid.UUID
	Actor     string
	Pod       string
	Command   string
	Tty       bool
	StartedAt time.Time
	EndedAt   pgtype.Timestamptz
	Outcome   string
	ExitCode  *int32
}

type Membership struct {
	UserID    uuid.UUID
	OwnerID   string
	Role      string
	CreatedAt time.Time
}

type PlatformDn struct {
	ID          int32
	CnameTarget string
	TxtPrefix   string
	UpdatedAt   time.Time
}

type PlatformRegistry struct {
	ID             int32
	Host           string
	Repository     string
	Username       string
	PasswordSealed []byte
	UpdatedAt      time.Time
	UpdatedBy      pgtype.UUID
	Insecure       bool
}

type Project struct {
	ID        uuid.UUID
	OwnerID   string
	Slug      string
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Session struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	TokenHash    []byte
	ActiveTeamID *string
	UserAgent    string
	Ip           string
	ExpiresAt    time.Time
	CreatedAt    time.Time
}

type Team struct {
	ID          string
	DisplayName string
	Email       string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type User struct {
	ID            uuid.UUID
	Email         *string
	DisplayName   string
	TotpSecret    *string
	TotpConfirmed bool
	CreatedAt     time.Time
	UpdatedAt     time.Time
	Username      string
	PasswordHash  []byte
	IsSuperuser   bool
}

type Variable struct {
	ID        uuid.UUID
	OwnerID   string
	AppID     uuid.UUID
	Key       string
	Value     string
	Sealed    []byte
	Secret    bool
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Volume struct {
	ID        uuid.UUID
	OwnerID   string
	AppID     uuid.UUID
	Name      string
	MountPath string
	SizeBytes int64
	Class     string
	CreatedAt time.Time
	UpdatedAt time.Time
}
