// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type App struct {
	ID             uuid.UUID
	OwnerID        string
	Name           string
	Namespace      string
	Image          string
	Replicas       int32
	Port           int32
	CpuRequest     string
	CpuLimit       string
	MemoryRequest  string
	MemoryLimit    string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	HealthPath     string
	HealthLiveness bool
	Source         string
	Internal       bool
	ProjectID      pgtype.UUID
	CanvasX        *int32
	CanvasY        *int32
	HttpsOnly      bool
	CnameOnly      bool
	RepoUrl        string
	RepoBranch     string
	RepoSubdir     string
	RunAsUser      int64
	Command        string
}

type AppLink struct {
	OwnerID   string
	FromAppID uuid.UUID
	ToAppID   uuid.UUID
	ViaKey    string
	CreatedAt time.Time
}

type Build struct {
	ID           uuid.UUID
	OwnerID      string
	AppID        uuid.UUID
	DeploymentID uuid.UUID
	RepoUrl      string
	RepoRef      string
	CommitSha    string
	Image        string
	Status       string
	Message      string
	Log          string
	StartedAt    time.Time
	FinishedAt   pgtype.Timestamptz
	JobName      string
}

type ClusterJoin struct {
	ID          int32
	ServerUrl   string
	TokenSealed []byte
	UpdatedAt   time.Time
	UpdatedBy   pgtype.UUID
}

type Deployment struct {
	ID         uuid.UUID
	OwnerID    string
	AppID      uuid.UUID
	Image      string
	Revision   string
	Status     string
	Message    string
	StartedAt  time.Time
	FinishedAt pgtype.Timestamptz
}

type Domain struct {
	ID           uuid.UUID
	OwnerID      string
	AppID        uuid.UUID
	Host         string
	Tls          bool
	Verified     bool
	CreatedAt    time.Time
	Managed      bool
	VerifiedAt   pgtype.Timestamptz
	VerifyTarget string
}

type Invitation struct {
	ID         uuid.UUID
	OwnerID    string
	Email      string
	Role       string
	TokenHash  []byte
	InvitedBy  pgtype.UUID
	ExpiresAt  time.Time
	AcceptedAt pgtype.Timestamptz
	CreatedAt  time.Time
}

type MagicLink struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	TokenHash  []byte
	ExpiresAt  time.Time
	ConsumedAt pgtype.Timestamptz
	CreatedAt  time.Time
}

type Membership struct {
	UserID    uuid.UUID
	OwnerID   string
	Role      string
	CreatedAt time.Time
}

type PlatformDn struct {
	ID          int32
	CnameTarget string
	TxtPrefix   string
	UpdatedAt   time.Time
}

type PlatformRegistry struct {
	ID             int32
	Host           string
	Repository     string
	Username       string
	PasswordSealed []byte
	UpdatedAt      time.Time
	UpdatedBy      pgtype.UUID
	Insecure       bool
}

type Project struct {
	ID        uuid.UUID
	OwnerID   string
	Slug      string
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Session struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	TokenHash    []byte
	ActiveTeamID *string
	UserAgent    string
	Ip           string
	ExpiresAt    time.Time
	CreatedAt    time.Time
}

type Team struct {
	ID          string
	DisplayName string
	Email       string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type User struct {
	ID            uuid.UUID
	Email         string
	DisplayName   string
	TotpSecret    *string
	TotpConfirmed bool
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type Variable struct {
	ID        uuid.UUID
	OwnerID   string
	AppID     uuid.UUID
	Key       string
	Value     string
	Sealed    []byte
	Secret    bool
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Volume struct {
	ID        uuid.UUID
	OwnerID   string
	AppID     uuid.UUID
	Name      string
	MountPath string
	SizeBytes int64
	Class     string
	CreatedAt time.Time
	UpdatedAt time.Time
}
