// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const clearProjectPositions = `-- name: ClearProjectPositions :execrows
UPDATE apps
SET canvas_x = NULL, canvas_y = NULL, updated_at = now()
WHERE owner_id = $1 AND project_id = $2
`

type ClearProjectPositionsParams struct {
	OwnerID   string
	ProjectID pgtype.UUID
}

// Forget every saved position in a project, so the next render lays it out
// again from the dependencies.
func (q *Queries) ClearProjectPositions(ctx context.Context, arg ClearProjectPositionsParams) (int64, error) {
	result, err := q.db.Exec(ctx, clearProjectPositions, arg.OwnerID, arg.ProjectID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createProject = `-- name: CreateProject :one

INSERT INTO projects (owner_id, slug, name)
VALUES ($1, $2, $3)
RETURNING id, owner_id, slug, name, created_at, updated_at
`

type CreateProjectParams struct {
	OwnerID string
	Slug    string
	Name    string
}

// Every query filters by owner_id, for the reason apps.sql gives: the scope is
// the check, not a duplicate of one.
func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject, arg.OwnerID, arg.Slug, arg.Name)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Slug,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :execrows
DELETE FROM projects WHERE owner_id = $1 AND id = $2
`

type DeleteProjectParams struct {
	OwnerID string
	ID      uuid.UUID
}

func (q *Queries) DeleteProject(ctx context.Context, arg DeleteProjectParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProject, arg.OwnerID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT id, owner_id, slug, name, created_at, updated_at FROM projects
WHERE owner_id = $1 AND id = $2
`

type GetProjectByIDParams struct {
	OwnerID string
	ID      uuid.UUID
}

func (q *Queries) GetProjectByID(ctx context.Context, arg GetProjectByIDParams) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByID, arg.OwnerID, arg.ID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Slug,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectBySlug = `-- name: GetProjectBySlug :one
SELECT id, owner_id, slug, name, created_at, updated_at FROM projects
WHERE owner_id = $1 AND slug = $2
`

type GetProjectBySlugParams struct {
	OwnerID string
	Slug    string
}

func (q *Queries) GetProjectBySlug(ctx context.Context, arg GetProjectBySlugParams) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectBySlug, arg.OwnerID, arg.Slug)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Slug,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAppsInProject = `-- name: ListAppsInProject :many
SELECT id, owner_id, name, namespace, image, replicas, port, cpu_request, cpu_limit, memory_request, memory_limit, created_at, updated_at, health_path, health_liveness, source, internal, project_id, canvas_x, canvas_y, https_only, cname_only, repo_url, repo_branch, repo_subdir, run_as_user, command, release_command, auto_deploy, webhook_secret, deploy_key, deploy_key_public, last_deployed_sha FROM apps
WHERE owner_id = $1 AND project_id = $2
ORDER BY name
`

type ListAppsInProjectParams struct {
	OwnerID   string
	ProjectID pgtype.UUID
}

func (q *Queries) ListAppsInProject(ctx context.Context, arg ListAppsInProjectParams) ([]App, error) {
	rows, err := q.db.Query(ctx, listAppsInProject, arg.OwnerID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []App{}
	for rows.Next() {
		var i App
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Namespace,
			&i.Image,
			&i.Replicas,
			&i.Port,
			&i.CpuRequest,
			&i.CpuLimit,
			&i.MemoryRequest,
			&i.MemoryLimit,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.HealthPath,
			&i.HealthLiveness,
			&i.Source,
			&i.Internal,
			&i.ProjectID,
			&i.CanvasX,
			&i.CanvasY,
			&i.HttpsOnly,
			&i.CnameOnly,
			&i.RepoUrl,
			&i.RepoBranch,
			&i.RepoSubdir,
			&i.RunAsUser,
			&i.Command,
			&i.ReleaseCommand,
			&i.AutoDeploy,
			&i.WebhookSecret,
			&i.DeployKey,
			&i.DeployKeyPublic,
			&i.LastDeployedSha,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAppsWithoutProject = `-- name: ListAppsWithoutProject :many
SELECT id, owner_id, name, namespace, image, replicas, port, cpu_request, cpu_limit, memory_request, memory_limit, created_at, updated_at, health_path, health_liveness, source, internal, project_id, canvas_x, canvas_y, https_only, cname_only, repo_url, repo_branch, repo_subdir, run_as_user, command, release_command, auto_deploy, webhook_secret, deploy_key, deploy_key_public, last_deployed_sha FROM apps
WHERE owner_id = $1 AND project_id IS NULL
ORDER BY name
`

// Apps that predate projects, or whose project was deleted.
//
// Returned separately rather than folded into a default project by the query,
// because assigning one is a write and a read should not have side effects
// that a caller cannot see.
func (q *Queries) ListAppsWithoutProject(ctx context.Context, ownerID string) ([]App, error) {
	rows, err := q.db.Query(ctx, listAppsWithoutProject, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []App{}
	for rows.Next() {
		var i App
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Namespace,
			&i.Image,
			&i.Replicas,
			&i.Port,
			&i.CpuRequest,
			&i.CpuLimit,
			&i.MemoryRequest,
			&i.MemoryLimit,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.HealthPath,
			&i.HealthLiveness,
			&i.Source,
			&i.Internal,
			&i.ProjectID,
			&i.CanvasX,
			&i.CanvasY,
			&i.HttpsOnly,
			&i.CnameOnly,
			&i.RepoUrl,
			&i.RepoBranch,
			&i.RepoSubdir,
			&i.RunAsUser,
			&i.Command,
			&i.ReleaseCommand,
			&i.AutoDeploy,
			&i.WebhookSecret,
			&i.DeployKey,
			&i.DeployKeyPublic,
			&i.LastDeployedSha,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjects = `-- name: ListProjects :many
SELECT p.id, p.owner_id, p.slug, p.name, p.created_at, p.updated_at, count(a.id) AS app_count
FROM projects p
LEFT JOIN apps a ON a.project_id = p.id
WHERE p.owner_id = $1
GROUP BY p.id
ORDER BY p.name
`

type ListProjectsRow struct {
	ID        uuid.UUID
	OwnerID   string
	Slug      string
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
	AppCount  int64
}

func (q *Queries) ListProjects(ctx context.Context, ownerID string) ([]ListProjectsRow, error) {
	rows, err := q.db.Query(ctx, listProjects, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectsRow{}
	for rows.Next() {
		var i ListProjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Slug,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AppCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveAppsWithoutProject = `-- name: MoveAppsWithoutProject :execrows
UPDATE apps
SET project_id = $2, updated_at = now()
WHERE owner_id = $1 AND project_id IS NULL
`

type MoveAppsWithoutProjectParams struct {
	OwnerID   string
	ProjectID pgtype.UUID
}

func (q *Queries) MoveAppsWithoutProject(ctx context.Context, arg MoveAppsWithoutProjectParams) (int64, error) {
	result, err := q.db.Exec(ctx, moveAppsWithoutProject, arg.OwnerID, arg.ProjectID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const renameProject = `-- name: RenameProject :one
UPDATE projects
SET name = $3, updated_at = now()
WHERE owner_id = $1 AND id = $2
RETURNING id, owner_id, slug, name, created_at, updated_at
`

type RenameProjectParams struct {
	OwnerID string
	ID      uuid.UUID
	Name    string
}

func (q *Queries) RenameProject(ctx context.Context, arg RenameProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, renameProject, arg.OwnerID, arg.ID, arg.Name)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Slug,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setAppPosition = `-- name: SetAppPosition :execrows
UPDATE apps
SET canvas_x = $3, canvas_y = $4, updated_at = now()
WHERE owner_id = $1 AND name = $2
`

type SetAppPositionParams struct {
	OwnerID string
	Name    string
	CanvasX *int32
	CanvasY *int32
}

func (q *Queries) SetAppPosition(ctx context.Context, arg SetAppPositionParams) (int64, error) {
	result, err := q.db.Exec(ctx, setAppPosition,
		arg.OwnerID,
		arg.Name,
		arg.CanvasX,
		arg.CanvasY,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setAppProject = `-- name: SetAppProject :execrows
UPDATE apps
SET project_id = $3, updated_at = now()
WHERE owner_id = $1 AND id = $2
`

type SetAppProjectParams struct {
	OwnerID   string
	ID        uuid.UUID
	ProjectID pgtype.UUID
}

func (q *Queries) SetAppProject(ctx context.Context, arg SetAppProjectParams) (int64, error) {
	result, err := q.db.Exec(ctx, setAppProject, arg.OwnerID, arg.ID, arg.ProjectID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
