// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	// One conditional UPDATE, like the magic link: checking first and writing after
	// leaves a window in which the same invitation is accepted twice.
	AcceptInvitation(ctx context.Context, tokenHash []byte) (AcceptInvitationRow, error)
	// Appended rather than replaced, so a build streaming its output does not have
	// to hold the whole log in memory to write any of it.
	AppendBuildLog(ctx context.Context, arg AppendBuildLogParams) error
	ClearClusterJoin(ctx context.Context) (int64, error)
	ClearPlatformRegistry(ctx context.Context) error
	// Forget every saved position in a project, so the next render lays it out
	// again from the dependencies.
	ClearProjectPositions(ctx context.Context, arg ClearProjectPositionsParams) (int64, error)
	// Marking consumed and reading the user are one statement, so there is no
	// window between the two in which a second request can also find the link
	// unconsumed. Expiry is in the same condition for the same reason: a link that
	// has just expired must fail here rather than in whatever checks it later.
	ConsumeMagicLink(ctx context.Context, tokenHash []byte) (User, error)
	CountApps(ctx context.Context, ownerID string) (int64, error)
	CountOwnersOfTeam(ctx context.Context, ownerID string) (int64, error)
	CreateApp(ctx context.Context, arg CreateAppParams) (App, error)
	CreateAppLink(ctx context.Context, arg CreateAppLinkParams) error
	// Builds. Owner-scoped in the row rather than through the deployment, because
	// the log is readable output and the scoping has to be checkable in the query
	// that reads it.
	CreateBuild(ctx context.Context, arg CreateBuildParams) (Build, error)
	// ---------------------------------------------------------- custom domains
	// Claims a hostname for an app, unverified.
	//
	// Deliberately not an upsert on host: the global unique index is what makes two
	// teams claiming one name an error rather than a silent transfer, and papering
	// over it here is exactly how a domain gets stolen.
	CreateCustomDomain(ctx context.Context, arg CreateCustomDomainParams) (Domain, error)
	CreateDeployment(ctx context.Context, arg CreateDeploymentParams) (Deployment, error)
	CreateMagicLink(ctx context.Context, arg CreateMagicLinkParams) (MagicLink, error)
	// Every query filters by owner_id, for the reason apps.sql gives: the scope is
	// the check, not a duplicate of one.
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error)
	// Every query filters by owner_id.
	//
	// This is not defensive duplication of an application-level check — it is the
	// check. A handler that forgets to scope produces no rows here rather than
	// another owner's data, and sqlc makes the parameter impossible to omit
	// because the generated signature requires it.
	CreateTeamRow(ctx context.Context, arg CreateTeamRowParams) (Team, error)
	// Storage attached to an app. Scoped by owner_id like every other resource
	// query: a handler that forgets to scope produces no rows here rather than
	// another team's storage.
	CreateVolume(ctx context.Context, arg CreateVolumeParams) (Volume, error)
	DeleteApp(ctx context.Context, arg DeleteAppParams) error
	DeleteCustomDomain(ctx context.Context, arg DeleteCustomDomainParams) (int64, error)
	DeleteExpiredInvitations(ctx context.Context) error
	DeleteExpiredMagicLinks(ctx context.Context) error
	DeleteExpiredSessions(ctx context.Context) error
	// Scoped by owner_id as well as id: an id from another team must not be
	// reachable by someone who happens to administer this one.
	DeleteInvitation(ctx context.Context, arg DeleteInvitationParams) (int64, error)
	// Withdraws the invitations somebody issued, used when they lose the authority
	// to have issued them. An administrator who leaves must not keep a live token
	// for an address they control.
	DeleteInvitationsByInviter(ctx context.Context, arg DeleteInvitationsByInviterParams) error
	// Releases an app's platform hostname.
	//
	// Deleting rather than leaving the row is what makes the feature reversible:
	// hostnames are globally unique, so a retired row keeps the name reserved
	// against every other app forever.
	DeleteManagedDomain(ctx context.Context, appID uuid.UUID) error
	DeleteMembership(ctx context.Context, arg DeleteMembershipParams) error
	DeleteProject(ctx context.Context, arg DeleteProjectParams) (int64, error)
	DeleteSessionByHash(ctx context.Context, tokenHash []byte) error
	DeleteSessionsForUser(ctx context.Context, userID uuid.UUID) error
	DeleteVariable(ctx context.Context, arg DeleteVariableParams) (int64, error)
	DeleteVolume(ctx context.Context, arg DeleteVolumeParams) (int64, error)
	// Deploys per day and outcome, for the overview chart.
	//
	// Counted in the database rather than by reading rows and tallying them in Go:
	// a busy month is thousands of deployments, and none of them are wanted here
	// except as a number.
	//
	// Days with no deploys are absent from this result. The caller fills them in;
	// see app.DeployActivity for why that cannot be skipped.
	DeployActivity(ctx context.Context, arg DeployActivityParams) ([]DeployActivityRow, error)
	FinishBuild(ctx context.Context, arg FinishBuildParams) (Build, error)
	FinishDeployment(ctx context.Context, arg FinishDeploymentParams) (Deployment, error)
	GetApp(ctx context.Context, arg GetAppParams) (App, error)
	GetAppByID(ctx context.Context, arg GetAppByIDParams) (App, error)
	GetBuild(ctx context.Context, arg GetBuildParams) (Build, error)
	GetBuildForDeployment(ctx context.Context, arg GetBuildForDeploymentParams) (Build, error)
	// The join settings are install-wide, so unlike every other query here these
	// take no owner_id. See the 00012 migration for why.
	GetClusterJoin(ctx context.Context) (ClusterJoin, error)
	GetCustomDomain(ctx context.Context, arg GetCustomDomainParams) (Domain, error)
	GetDeployment(ctx context.Context, arg GetDeploymentParams) (Deployment, error)
	// Reads an invitation without spending it, so a signed-out visitor can be sent
	// a sign-in link to the address it names. token_hash is not among the columns,
	// for the same reason it is absent from ListPendingInvitations.
	GetInvitationByHash(ctx context.Context, tokenHash []byte) (GetInvitationByHashRow, error)
	GetManagedDomain(ctx context.Context, appID uuid.UUID) (Domain, error)
	GetMembership(ctx context.Context, arg GetMembershipParams) (Membership, error)
	// Install-wide DNS settings. No owner_id, for the reason cluster_join has
	// none: they configure one controller shared by every team.
	GetPlatformDNS(ctx context.Context) (PlatformDn, error)
	// The install's image registry. No owner_id, for the reason platform_dns has
	// none: one registry serves every team's builds.
	GetPlatformRegistry(ctx context.Context) (PlatformRegistry, error)
	GetProjectByID(ctx context.Context, arg GetProjectByIDParams) (Project, error)
	GetProjectBySlug(ctx context.Context, arg GetProjectBySlugParams) (Project, error)
	GetSession(ctx context.Context, id uuid.UUID) (Session, error)
	// The team is joined in because the request that carries this cookie needs the
	// owner it resolves to, and a second round trip per request buys nothing. The
	// join is LEFT: a session whose team was deleted still exists, it just has no
	// owner to act as.
	//
	// Expiry is filtered in SQL rather than in Go so that an expired row can never
	// be treated as valid by a caller that forgets to check.
	// Resolves a session only while the membership behind it still exists.
	//
	// The join to memberships is the security boundary, not decoration. Revoking
	// sessions imperatively when someone is removed would work only for the call
	// sites that remember to do it, and would still miss membership lost by
	// cascade. Joining makes a departed member's cookie stop resolving the instant
	// the row goes, by whatever route it went.
	//
	// INNER JOIN on teams too: a session with no active team resolves to no owner,
	// and returning a row the caller must then remember to reject is how that
	// check gets skipped.
	GetSessionByHash(ctx context.Context, tokenHash []byte) (GetSessionByHashRow, error)
	GetTeam(ctx context.Context, id string) (Team, error)
	GetTeamRow(ctx context.Context, id string) (Team, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetVolume(ctx context.Context, arg GetVolumeParams) (Volume, error)
	// Expansion only, enforced in the WHERE clause rather than by reading the row
	// and comparing in Go: a check the caller performs is one a caller can skip,
	// and Kubernetes cannot shrink a claim afterwards to undo it.
	GrowVolume(ctx context.Context, arg GrowVolumeParams) (int64, error)
	ListAppLinks(ctx context.Context, ownerID string) ([]ListAppLinksRow, error)
	ListApps(ctx context.Context, ownerID string) ([]App, error)
	ListAppsInProject(ctx context.Context, arg ListAppsInProjectParams) ([]App, error)
	// Apps that predate projects, or whose project was deleted.
	//
	// Returned separately rather than folded into a default project by the query,
	// because assigning one is a write and a read should not have side effects
	// that a caller cannot see.
	ListAppsWithoutProject(ctx context.Context, ownerID string) ([]App, error)
	ListCustomDomains(ctx context.Context, arg ListCustomDomainsParams) ([]Domain, error)
	ListDeployments(ctx context.Context, arg ListDeploymentsParams) ([]Deployment, error)
	ListDomainsByApp(ctx context.Context, appID uuid.UUID) ([]Domain, error)
	ListMembersOfTeam(ctx context.Context, ownerID string) ([]ListMembersOfTeamRow, error)
	ListMembershipsForUser(ctx context.Context, userID uuid.UUID) ([]ListMembershipsForUserRow, error)
	// The columns are named rather than starred, and token_hash is not among them.
	// This list feeds the team page, and a hash that never leaves the database
	// cannot be rendered into it by a template that innocently prints a struct.
	ListPendingInvitations(ctx context.Context, ownerID string) ([]ListPendingInvitationsRow, error)
	ListProjects(ctx context.Context, ownerID string) ([]ListProjectsRow, error)
	// Joined to apps so the activity feed can name the workload without a second
	// round trip per row. The join is on app_id AND owner_id: joining on app_id
	// alone would be correct today and wrong the moment more than one owner exists.
	ListRecentDeployments(ctx context.Context, arg ListRecentDeploymentsParams) ([]ListRecentDeploymentsRow, error)
	// Every build still claiming to run, oldest first. Not owner-scoped: this
	// feeds the reconciler, which is the platform settling its own records rather
	// than a team reading theirs.
	ListRunningBuilds(ctx context.Context) ([]Build, error)
	ListVariablesForApp(ctx context.Context, appID uuid.UUID) ([]Variable, error)
	ListVolumesForApp(ctx context.Context, appID uuid.UUID) ([]Volume, error)
	// A role change reads the owner count and then writes; taking the team row
	// first serialises those pairs, so two concurrent demotions cannot both see
	// two owners and both proceed.
	LockTeam(ctx context.Context, id string) (Team, error)
	MoveAppsWithoutProject(ctx context.Context, arg MoveAppsWithoutProjectParams) (int64, error)
	RenameProject(ctx context.Context, arg RenameProjectParams) (Project, error)
	ReplaceAppLinks(ctx context.Context, arg ReplaceAppLinksParams) error
	// Hostnames that may actually be routed to.
	//
	// A managed host is routable because the platform issued it; a custom one only
	// once it is proven. This is the query the Ingress is built from, so the gate
	// lives here rather than in a caller that might forget it.
	RoutableHostsForApp(ctx context.Context, appID uuid.UUID) ([]string, error)
	SetAppCommand(ctx context.Context, arg SetAppCommandParams) (App, error)
	SetAppHealth(ctx context.Context, arg SetAppHealthParams) (App, error)
	// The image a build produced. Separate from UpdateApp because a build sets
	// only this: the replicas and limits a person configured are not a build's to
	// overwrite, and passing them through would make every build a chance to.
	SetAppImage(ctx context.Context, arg SetAppImageParams) (App, error)
	SetAppNetworking(ctx context.Context, arg SetAppNetworkingParams) (int64, error)
	SetAppPosition(ctx context.Context, arg SetAppPositionParams) (int64, error)
	SetAppProject(ctx context.Context, arg SetAppProjectParams) (int64, error)
	SetAppReplicas(ctx context.Context, arg SetAppReplicasParams) (App, error)
	// Recorded by a build, which is the only thing that can discover it.
	SetAppRunAsUser(ctx context.Context, arg SetAppRunAsUserParams) error
	SetBuildJob(ctx context.Context, arg SetBuildJobParams) error
	SetClusterJoin(ctx context.Context, arg SetClusterJoinParams) (ClusterJoin, error)
	SetPlatformDNS(ctx context.Context, arg SetPlatformDNSParams) (PlatformDn, error)
	SetPlatformRegistry(ctx context.Context, arg SetPlatformRegistryParams) (PlatformRegistry, error)
	SetSessionTeam(ctx context.Context, arg SetSessionTeamParams) error
	// Retires the deployments a new one replaces.
	//
	// Only rows that never reached a terminal state: a finished deployment already
	// says what happened to it, and rewriting that would lose the difference
	// between one that was replaced and one that failed.
	SupersedeDeployments(ctx context.Context, arg SupersedeDeploymentsParams) (int64, error)
	UpdateApp(ctx context.Context, arg UpdateAppParams) (App, error)
	// Re-inviting replaces the pending invitation rather than adding a second one,
	// so the token in the older mail stops working. Two live tokens for one address
	// would mean revoking the invitation on screen leaves the other one usable.
	UpsertInvitation(ctx context.Context, arg UpsertInvitationParams) (uuid.UUID, error)
	// Platform-issued hostnames. Custom domains get their own queries when that
	// sub-project lands; keeping them in one file rather than in apps.sql is so
	// that apps.sql stays about apps.
	// Issues or reissues the platform hostname for an app.
	//
	// The conflict target is the partial index, so a second call for the same app
	// moves its hostname rather than adding one. A collision on the global host
	// index is a different conflict and is deliberately left to raise, because two
	// apps claiming one hostname is a real error, not something to paper over.
	//
	// verified is true because a name the platform issued needs no proof of
	// ownership; requiring proof would mean inventing a verification step for a
	// name we already control.
	UpsertManagedDomain(ctx context.Context, arg UpsertManagedDomainParams) (Domain, error)
	UpsertMembership(ctx context.Context, arg UpsertMembershipParams) (Membership, error)
	// Users and sessions carry no owner_id: a person exists before they belong to
	// any team. Memberships and invitations do, and stay scoped by it like
	// everything else.
	UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error)
	// Environment variables, one row each so a secret can be sealed while its
	// neighbour stays readable.
	// Upsert rather than insert: setting a variable that already exists is what a
	// person means by editing one, and a separate update path would need the
	// caller to know which case they are in.
	UpsertVariable(ctx context.Context, arg UpsertVariableParams) (Variable, error)
	// Marks a claim proven. Scoped by owner as well as id: verifying is a write,
	// and a write on somebody else's row is the thing owner scoping exists for.
	VerifyCustomDomain(ctx context.Context, arg VerifyCustomDomainParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
