// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	// Appended rather than replaced, so a build streaming its output does not have
	// to hold the whole log in memory to write any of it.
	AppendBuildLog(ctx context.Context, arg AppendBuildLogParams) error
	ClearClusterJoin(ctx context.Context) (int64, error)
	ClearPlatformRegistry(ctx context.Context) error
	// Forget every saved position in a project, so the next render lays it out
	// again from the dependencies.
	ClearProjectPositions(ctx context.Context, arg ClearProjectPositionsParams) (int64, error)
	CountApps(ctx context.Context, ownerID string) (int64, error)
	CountOwnersOfTeam(ctx context.Context, ownerID string) (int64, error)
	CountSuperusers(ctx context.Context) (int64, error)
	CreateAPIToken(ctx context.Context, arg CreateAPITokenParams) (ApiToken, error)
	CreateApp(ctx context.Context, arg CreateAppParams) (App, error)
	CreateAppLink(ctx context.Context, arg CreateAppLinkParams) error
	// Builds. Owner-scoped in the row rather than through the deployment, because
	// the log is readable output and the scoping has to be checkable in the query
	// that reads it.
	CreateBuild(ctx context.Context, arg CreateBuildParams) (Build, error)
	// ---------------------------------------------------------- custom domains
	// Claims a hostname for an app, unverified.
	//
	// Deliberately not an upsert on host: the global unique index is what makes two
	// teams claiming one name an error rather than a silent transfer, and papering
	// over it here is exactly how a domain gets stolen.
	CreateCustomDomain(ctx context.Context, arg CreateCustomDomainParams) (Domain, error)
	CreateDeployment(ctx context.Context, arg CreateDeploymentParams) (Deployment, error)
	// Every query filters by owner_id, for the reason apps.sql gives: the scope is
	// the check, not a duplicate of one.
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error)
	// Every query filters by owner_id.
	//
	// This is not defensive duplication of an application-level check — it is the
	// check. A handler that forgets to scope produces no rows here rather than
	// another owner's data, and sqlc makes the parameter impossible to omit
	// because the generated signature requires it.
	CreateTeamRow(ctx context.Context, arg CreateTeamRowParams) (Team, error)
	// Users and sessions carry no owner_id: a person exists before they belong to
	// any team. Memberships do, and stay scoped by it like everything else.
	//
	// Sign-in is username and password. There is no query here that looks a person
	// up by address, because an address no longer identifies anybody — it is a
	// contact field, and the credential is the password hash.
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// Storage attached to an app. Scoped by owner_id like every other resource
	// query: a handler that forgets to scope produces no rows here rather than
	// another team's storage.
	CreateVolume(ctx context.Context, arg CreateVolumeParams) (Volume, error)
	// Deleted by id, scoped by user and team so that holding an id from somewhere
	// else is not enough to revoke somebody's credential.
	DeleteAPIToken(ctx context.Context, arg DeleteAPITokenParams) error
	DeleteApp(ctx context.Context, arg DeleteAppParams) error
	// Removes the destination.
	//
	// Policies are left in place on purpose. They describe what an owner wants
	// backed up, which does not stop being true because the storage was
	// reconfigured; deleting them would mean re-entering every schedule after
	// rotating a bucket credential.
	DeleteBackupDestination(ctx context.Context, ownerID string) error
	DeleteBackupPolicy(ctx context.Context, arg DeleteBackupPolicyParams) (int64, error)
	DeleteCustomDomain(ctx context.Context, arg DeleteCustomDomainParams) (int64, error)
	DeleteExpiredAPITokens(ctx context.Context) error
	DeleteExpiredSessions(ctx context.Context) error
	// Releases an app's platform hostname.
	//
	// Deleting rather than leaving the row is what makes the feature reversible:
	// hostnames are globally unique, so a retired row keeps the name reserved
	// against every other app forever.
	DeleteManagedDomain(ctx context.Context, appID uuid.UUID) error
	DeleteMembership(ctx context.Context, arg DeleteMembershipParams) error
	DeleteProject(ctx context.Context, arg DeleteProjectParams) (int64, error)
	DeleteSessionByHash(ctx context.Context, tokenHash []byte) error
	DeleteSessionsForUser(ctx context.Context, userID uuid.UUID) error
	DeleteUser(ctx context.Context, id uuid.UUID) (int64, error)
	DeleteVariable(ctx context.Context, arg DeleteVariableParams) (int64, error)
	DeleteVolume(ctx context.Context, arg DeleteVolumeParams) (int64, error)
	// Deploys per day and outcome, for the overview chart.
	//
	// Counted in the database rather than by reading rows and tallying them in Go:
	// a busy month is thousands of deployments, and none of them are wanted here
	// except as a number.
	//
	// Days with no deploys are absent from this result. The caller fills them in;
	// see app.DeployActivity for why that cannot be skipped.
	DeployActivity(ctx context.Context, arg DeployActivityParams) ([]DeployActivityRow, error)
	// Whether this deployment is still the one that should be acting.
	//
	// For the steps that cannot be folded into a single statement: running a
	// release command and applying to the cluster. Checking immediately before
	// each does not make them atomic, but it closes the window from "the length of
	// a build" — minutes — to the microseconds between this query and the next
	// call, which is the difference between a race that happens and one that does
	// not.
	//
	// True for the nil id, for the reason given on SetBuiltImage.
	DeploymentIsCurrent(ctx context.Context, arg DeploymentIsCurrentParams) (bool, error)
	// Written on a detached, bounded context at teardown.
	//
	// Scoped by owner as well as id: an audit row is not something a caller should
	// be able to close on somebody else's behalf by holding an id.
	EndExecSession(ctx context.Context, arg EndExecSessionParams) error
	// Seeding the superuser is an upsert on the name, and it deliberately does not
	// touch password_hash. Re-running the process must not put the built-in default
	// back over a password somebody has since changed — that would make every
	// restart a silent credential reset.
	EnsureSuperuser(ctx context.Context, arg EnsureSuperuserParams) (User, error)
	FinishBuild(ctx context.Context, arg FinishBuildParams) (Build, error)
	// Only a deployment that is still running can be finished.
	//
	// A retired row has to stay retired. Two deploys of one app overlap whenever a
	// redeploy starts while an earlier build is still going, and the older
	// goroutine reaching this line last would otherwise flip its superseded row
	// back to 'active' — leaving an app with two active deployments, one of which
	// names an image nobody is running.
	//
	// Returns no row when it matched nothing, which the caller reads as "something
	// newer took over" rather than as a failure.
	FinishDeployment(ctx context.Context, arg FinishDeploymentParams) (Deployment, error)
	// Resolves a token only while the membership behind it still exists, and
	// returns the role in the same row.
	//
	// This is GetSessionByHash with a different credential, and it is deliberately
	// the same shape in all three respects that matter:
	//
	// The join to memberships is the security boundary, not decoration. A token
	// outlives the browser that minted it by design, so "revoke the credential when
	// someone leaves" is a step that will be missed — here it cannot be, because a
	// departed member's token stops resolving the instant the membership row goes,
	// by whatever route it went, including cascade.
	//
	// The row is deleted by that same cascade rather than merely orphaned; the
	// schema carries a composite foreign key onto memberships to ensure it. This
	// join is therefore defence in depth rather than the whole mechanism, which is
	// the right way round: were it the only mechanism, removing somebody would
	// suspend their tokens rather than revoke them, and re-adding them would bring
	// every one of those credentials back.
	//
	// The role comes back with the credential because the query that proves the
	// token is live is the query that says what it may do. Looking the role up
	// separately gives two answers that can disagree, and the window between them
	// is the one where a demoted member still writes.
	//
	// Expiry is filtered in SQL rather than in Go so that an expired row can never
	// be treated as valid by a caller that forgets to check. NULL means no expiry,
	// which is the common case for a credential living in CI.
	GetAPITokenByHash(ctx context.Context, tokenHash []byte) (GetAPITokenByHashRow, error)
	GetApp(ctx context.Context, arg GetAppParams) (App, error)
	GetAppByID(ctx context.Context, arg GetAppByIDParams) (App, error)
	GetBackupDestination(ctx context.Context, ownerID string) (BackupDestination, error)
	GetBackupPolicy(ctx context.Context, appID uuid.UUID) (BackupPolicy, error)
	GetBuild(ctx context.Context, arg GetBuildParams) (Build, error)
	GetBuildForDeployment(ctx context.Context, arg GetBuildForDeploymentParams) (Build, error)
	// The join settings are install-wide, so unlike every other query here these
	// take no owner_id. See the 00012 migration for why.
	GetClusterJoin(ctx context.Context) (ClusterJoin, error)
	GetCustomDomain(ctx context.Context, arg GetCustomDomainParams) (Domain, error)
	GetDeployment(ctx context.Context, arg GetDeploymentParams) (Deployment, error)
	GetManagedDomain(ctx context.Context, appID uuid.UUID) (Domain, error)
	GetMembership(ctx context.Context, arg GetMembershipParams) (Membership, error)
	// Install-wide DNS settings. No owner_id, for the reason cluster_join has
	// none: they configure one controller shared by every team.
	GetPlatformDNS(ctx context.Context) (PlatformDn, error)
	// The install's image registry. No owner_id, for the reason platform_dns has
	// none: one registry serves every team's builds.
	GetPlatformRegistry(ctx context.Context) (PlatformRegistry, error)
	GetProjectByID(ctx context.Context, arg GetProjectByIDParams) (Project, error)
	GetProjectBySlug(ctx context.Context, arg GetProjectBySlugParams) (Project, error)
	GetSession(ctx context.Context, id uuid.UUID) (Session, error)
	// The team is joined in because the request that carries this cookie needs the
	// owner it resolves to, and a second round trip per request buys nothing. The
	// join is LEFT: a session whose team was deleted still exists, it just has no
	// owner to act as.
	//
	// Expiry is filtered in SQL rather than in Go so that an expired row can never
	// be treated as valid by a caller that forgets to check.
	// Resolves a session only while the membership behind it still exists.
	//
	// The join to memberships is the security boundary, not decoration. Revoking
	// sessions imperatively when someone is removed would work only for the call
	// sites that remember to do it, and would still miss membership lost by
	// cascade. Joining makes a departed member's cookie stop resolving the instant
	// the row goes, by whatever route it went.
	//
	// INNER JOIN on teams too: a session with no active team resolves to no owner,
	// and returning a row the caller must then remember to reject is how that
	// check gets skipped.
	GetSessionByHash(ctx context.Context, tokenHash []byte) (GetSessionByHashRow, error)
	GetTeam(ctx context.Context, id string) (Team, error)
	GetTeamRow(ctx context.Context, id string) (Team, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetVolume(ctx context.Context, arg GetVolumeParams) (Volume, error)
	// Expansion only, enforced in the WHERE clause rather than by reading the row
	// and comparing in Go: a check the caller performs is one a caller can skip,
	// and Kubernetes cannot shrink a claim afterwards to undo it.
	GrowVolume(ctx context.Context, arg GrowVolumeParams) (int64, error)
	// The list a person prunes from. Scoped by both user and team: a token is a
	// credential of one person acting as one team, and listing another person's is
	// neither useful nor theirs to see.
	ListAPITokens(ctx context.Context, arg ListAPITokensParams) ([]ApiToken, error)
	ListAppLinks(ctx context.Context, ownerID string) ([]ListAppLinksRow, error)
	ListApps(ctx context.Context, ownerID string) ([]App, error)
	ListAppsInProject(ctx context.Context, arg ListAppsInProjectParams) ([]App, error)
	// Apps that predate projects, or whose project was deleted.
	//
	// Returned separately rather than folded into a default project by the query,
	// because assigning one is a write and a read should not have side effects
	// that a caller cannot see.
	ListAppsWithoutProject(ctx context.Context, ownerID string) ([]App, error)
	// Candidates a push might affect.
	//
	// Deliberately NOT filtered by repository URL in SQL. The URL in a webhook
	// payload is attacker-controlled — anybody can POST a body naming any
	// repository — so it must never be the thing that selects which app is
	// deployed. The signature does that: every candidate is tried and only the one
	// whose secret verifies is acted on, which is why this returns them all.
	ListAutoDeployApps(ctx context.Context) ([]App, error)
	ListAutoDeployAppsForOwner(ctx context.Context, ownerID string) ([]App, error)
	// Every policy an owner has, with the app it belongs to.
	//
	// Joined rather than returning app ids for the caller to look up one at a
	// time: the settings page lists these together, and the n+1 is the whole of
	// what that page does.
	ListBackupPolicies(ctx context.Context, ownerID string) ([]ListBackupPoliciesRow, error)
	// Policies that are switched on, for reconciling schedules into the cluster
	// at startup. A disabled one is reconciled too — as a schedule to remove —
	// which is why this does not filter on enabled.
	ListBackupPoliciesForReconcile(ctx context.Context) ([]ListBackupPoliciesForReconcileRow, error)
	ListCustomDomains(ctx context.Context, arg ListCustomDomainsParams) ([]Domain, error)
	// Joined to apps for the source, which the deployment row does not carry.
	//
	// Correct for old rows as well as new ones: apps.source is written by
	// CreateApp and by nothing else, so an app's source cannot have been anything
	// different when an earlier deployment ran.
	ListDeployments(ctx context.Context, arg ListDeploymentsParams) ([]ListDeploymentsRow, error)
	ListDomainsByApp(ctx context.Context, appID uuid.UUID) ([]Domain, error)
	ListExecSessions(ctx context.Context, arg ListExecSessionsParams) ([]ListExecSessionsRow, error)
	ListMembersOfTeam(ctx context.Context, ownerID string) ([]ListMembersOfTeamRow, error)
	ListMembershipsForUser(ctx context.Context, userID uuid.UUID) ([]ListMembershipsForUserRow, error)
	// The sessions that have not ended.
	//
	// The signal this table exists to carry, and it needs a query or it is a signal
	// nobody can read. Two different situations land here and both are worth
	// seeing:
	//
	//   * somebody is in a container RIGHT NOW, which is what an incident asks
	//   * a session ended in a way this process never observed — it was killed
	//     with the process, or the machine went away — so nothing ever closed it
	//
	// They are deliberately not distinguished, because nothing observed the
	// difference. A row that has been open for four seconds is somebody working; a
	// row open for four days is a session nobody will ever account for, and the
	// started_at is what tells them apart.
	//
	// Backed by the partial index on (owner_id) WHERE ended_at IS NULL.
	ListOpenExecSessions(ctx context.Context, ownerID string) ([]ListOpenExecSessionsRow, error)
	ListProjects(ctx context.Context, ownerID string) ([]ListProjectsRow, error)
	// Joined to apps so the activity feed can name the workload without a second
	// round trip per row. The join is on app_id AND owner_id: joining on app_id
	// alone would be correct today and wrong the moment more than one owner exists.
	ListRecentDeployments(ctx context.Context, arg ListRecentDeploymentsParams) ([]ListRecentDeploymentsRow, error)
	// Every build still claiming to run, oldest first. Not owner-scoped: this
	// feeds the reconciler, which is the platform settling its own records rather
	// than a team reading theirs.
	ListRunningBuilds(ctx context.Context) ([]Build, error)
	ListUsers(ctx context.Context) ([]User, error)
	ListVariablesForApp(ctx context.Context, appID uuid.UUID) ([]Variable, error)
	ListVolumesForApp(ctx context.Context, appID uuid.UUID) ([]Volume, error)
	// Serialises the deploys of one app, and nothing else.
	//
	// beginDeployment retires the previous deployment and then opens a new one.
	// Two of those interleaving — two clicks, or a webhook arriving on top of a
	// redeploy — each retire nothing, because neither has created its row yet, and
	// then each create one. The app ends up with two deployments that both believe
	// they are current, which is the same failure by a different route.
	//
	// Taking the app's own row first makes the pair atomic. It blocks only another
	// deploy of the same app.
	LockAppForDeploy(ctx context.Context, arg LockAppForDeployParams) (uuid.UUID, error)
	// A role change reads the owner count and then writes; taking the team row
	// first serialises those pairs, so two concurrent demotions cannot both see
	// two owners and both proceed.
	LockTeam(ctx context.Context, id string) (Team, error)
	MoveAppsWithoutProject(ctx context.Context, arg MoveAppsWithoutProjectParams) (int64, error)
	RenameProject(ctx context.Context, arg RenameProjectParams) (Project, error)
	ReplaceAppLinks(ctx context.Context, arg ReplaceAppLinksParams) error
	// Hostnames that may actually be routed to, and whether the platform issued
	// each one.
	//
	// A managed host is routable because the platform issued it; a custom one only
	// once it is proven. This is the query the Ingress is built from, so the gate
	// lives here rather than in a caller that might forget it.
	//
	// managed comes back with the host because it decides which certificate serves
	// the name, and it is the recorded fact rather than a suffix comparison — see
	// 00002. A caller that had only the hostname would have to re-derive it from
	// the current app domain, which is the derivation that column exists to avoid.
	RoutableHostsForApp(ctx context.Context, appID uuid.UUID) ([]RoutableHostsForAppRow, error)
	SetAppAutoDeploy(ctx context.Context, arg SetAppAutoDeployParams) (App, error)
	SetAppCommand(ctx context.Context, arg SetAppCommandParams) (App, error)
	SetAppDeployKey(ctx context.Context, arg SetAppDeployKeyParams) error
	SetAppHealth(ctx context.Context, arg SetAppHealthParams) (App, error)
	SetAppLastDeployedSHA(ctx context.Context, arg SetAppLastDeployedSHAParams) error
	SetAppNetworking(ctx context.Context, arg SetAppNetworkingParams) (int64, error)
	SetAppPosition(ctx context.Context, arg SetAppPositionParams) (int64, error)
	SetAppProject(ctx context.Context, arg SetAppProjectParams) (int64, error)
	SetAppReleaseCommand(ctx context.Context, arg SetAppReleaseCommandParams) (App, error)
	SetAppReplicas(ctx context.Context, arg SetAppReplicasParams) (App, error)
	// Recorded by a build, which is the only thing that can discover it.
	SetAppRunAsUser(ctx context.Context, arg SetAppRunAsUserParams) error
	// Both together, because they are one decision.
	//
	// A port is what traffic is routed to and internal is whether any is routed at
	// all; setting one without the other produces states nobody asked for — an
	// internal app that just acquired a port, or a public app whose port was
	// cleared and which therefore has a hostname routing to nothing. The caller
	// passes both and the pair is written atomically.
	//
	// Narrow rather than reusing UpdateApp, which also carries image and replicas.
	// Those belong to the deploy and the scale paths respectively, and a query that
	// can write all five is one that will eventually write a stale image while
	// changing a port.
	SetAppService(ctx context.Context, arg SetAppServiceParams) (App, error)
	SetAppWebhookSecret(ctx context.Context, arg SetAppWebhookSecretParams) error
	SetBuildJob(ctx context.Context, arg SetBuildJobParams) error
	// The image a build produced. Separate from UpdateApp because a build sets
	// only this: the replicas and limits a person configured are not a build's to
	// overwrite, and passing them through would make every build a chance to.
	//
	// Written only while the deployment that produced it is still current. Both
	// halves of an overlapping pair finish by writing this column, in completion
	// order rather than start order, so without the guard an app is left recorded
	// as running the older build while its own newest deployment row names the
	// newer one. That is a rollback menu offering an image nobody is running.
	// beginDeployment already retires the earlier deployment; this is what makes
	// the retirement bite.
	//
	// Guarded here rather than checked in Go because a check and a write are two
	// statements, and the whole problem is what happens between two statements.
	//
	// The nil id is the case where CreateDeployment itself failed and the deploy
	// went ahead without history. There is nothing that could have superseded it,
	// so the image is written rather than silently dropped.
	// Every column qualified: the correlated subquery puts two tables in scope,
	// and a bare owner_id is then ambiguous rather than merely unclear.
	SetBuiltImage(ctx context.Context, arg SetBuiltImageParams) (App, error)
	SetClusterJoin(ctx context.Context, arg SetClusterJoinParams) (ClusterJoin, error)
	// The image a build produced, recorded on the deployment that produced it.
	//
	// CreateDeployment can only store the image the app had when the deploy was
	// asked for, which for a git app is the *previous* deploy's image: the build
	// that makes the new one has not run yet. Left there, every row in the history
	// names the image it replaced, and rolling back to what a row says would
	// redeploy the wrong one.
	SetDeploymentImage(ctx context.Context, arg SetDeploymentImageParams) (Deployment, error)
	// Written whether the release passed or failed.
	//
	// A failed release's reason is in its log, and dropping the log on failure is
	// how a vetoed deploy becomes impossible to explain — which is the one case
	// somebody actually needs it.
	SetDeploymentRelease(ctx context.Context, arg SetDeploymentReleaseParams) error
	SetPlatformDNS(ctx context.Context, arg SetPlatformDNSParams) (PlatformDn, error)
	SetPlatformRegistry(ctx context.Context, arg SetPlatformRegistryParams) (PlatformRegistry, error)
	SetSessionTeam(ctx context.Context, arg SetSessionTeamParams) error
	SetUserPassword(ctx context.Context, arg SetUserPasswordParams) error
	// Written BEFORE the stream opens, so a session that dies during attach has
	// already been recorded. See 00025 for why the ordering is load-bearing.
	StartExecSession(ctx context.Context, arg StartExecSessionParams) (ExecSession, error)
	// Retires the deployments a new one replaces.
	//
	// Only rows that never reached a terminal state: a finished deployment already
	// says what happened to it, and rewriting that would lose the difference
	// between one that was replaced and one that failed.
	SupersedeDeployments(ctx context.Context, arg SupersedeDeploymentsParams) (int64, error)
	// Best-effort bookkeeping on a hot path. Separate from GetAPITokenByHash rather
	// than folded into it with a CTE: resolving a credential is a read, and making
	// it a write puts every authenticated API request into a row lock on the same
	// token. A CI job running twenty parallel deploys would serialise on it.
	TouchAPIToken(ctx context.Context, id uuid.UUID) error
	UpdateApp(ctx context.Context, arg UpdateAppParams) (App, error)
	// Where an owner's backups go, and what gets backed up.
	//
	// What is absent: any record of the snapshots themselves. Those live in the
	// restic repository, which is the only thing that knows what it actually holds
	// — the same split the rest of this engine keeps between the database, which
	// says what should exist, and the runtime, which says how it is doing. A table
	// of snapshot rows would be a cache that disagrees with the repository the
	// first time a job is killed between writing a snapshot and reporting it, and
	// it would disagree in the direction that matters: claiming a backup exists.
	UpsertBackupDestination(ctx context.Context, arg UpsertBackupDestinationParams) (BackupDestination, error)
	UpsertBackupPolicy(ctx context.Context, arg UpsertBackupPolicyParams) (BackupPolicy, error)
	// Platform-issued hostnames. Custom domains get their own queries when that
	// sub-project lands; keeping them in one file rather than in apps.sql is so
	// that apps.sql stays about apps.
	// Issues or reissues the platform hostname for an app.
	//
	// The conflict target is the partial index, so a second call for the same app
	// moves its hostname rather than adding one. A collision on the global host
	// index is a different conflict and is deliberately left to raise, because two
	// apps claiming one hostname is a real error, not something to paper over.
	//
	// verified is true because a name the platform issued needs no proof of
	// ownership; requiring proof would mean inventing a verification step for a
	// name we already control.
	UpsertManagedDomain(ctx context.Context, arg UpsertManagedDomainParams) (Domain, error)
	UpsertMembership(ctx context.Context, arg UpsertMembershipParams) (Membership, error)
	// Environment variables, one row each so a secret can be sealed while its
	// neighbour stays readable.
	// Upsert rather than insert: setting a variable that already exists is what a
	// person means by editing one, and a separate update path would need the
	// caller to know which case they are in.
	UpsertVariable(ctx context.Context, arg UpsertVariableParams) (Variable, error)
	// Marks a claim proven. Scoped by owner as well as id: verifying is a write,
	// and a write on somebody else's row is the thing owner scoping exists for.
	VerifyCustomDomain(ctx context.Context, arg VerifyCustomDomainParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
